import type { TranslationResources } from './types';

export const de: TranslationResources = {
  auth: {
    environment: {
      productionRequired: 'Dieses Konto kann nur die Produktionsumgebung verwenden. Melden Sie sich erneut an.',
    },
    forgotPassword: {
      codeSent: 'Bestätigungscode gesendet',
      email: 'E-Mail',
      explanation: 'Geben Sie Ihre E-Mail ein, um einen sechsstelligen Bestätigungscode zu erhalten.',
      sendCode: 'Code senden',
      title: 'Passwort vergessen',
      validation: {
        emailInvalid: 'Geben Sie eine gültige E-Mail-Adresse ein.',
        emailRequired: 'E-Mail ist erforderlich.',
      },
    },
    login: {
      createAccount: 'Konto erstellen',
      description: 'Melden Sie sich an, um FastRep weiter zu nutzen.',
      email: 'E-Mail',
      forgotPassword: 'Passwort vergessen?',
      invalidCredentials: 'Die E-Mail-Adresse oder das Passwort ist falsch.',
      logIn: 'Anmelden',
      password: 'Passwort',
      title: 'Willkommen zurück',
      validation: {
        emailInvalid: 'Geben Sie eine gültige E-Mail-Adresse ein.',
        emailRequired: 'E-Mail ist erforderlich.',
        passwordMax: 'Das Passwort darf höchstens 128 Zeichen enthalten.',
        passwordMin: 'Das Passwort muss mindestens 8 Zeichen enthalten.',
        passwordRequired: 'Das Passwort ist erforderlich.',
      },
    },
    registration: {
      alreadyHaveAccount: 'Sie haben bereits ein Konto?',
      confirmPassword: 'Passwort bestätigen',
      createAccount: 'Konto erstellen',
      email: 'E-Mail',
      fullName: 'Vollständiger Name',
      logIn: 'Anmelden',
      password: 'Passwort',
      subtitle: 'Erstellen Sie Ihr FastRep-Konto, um loszulegen.',
      title: 'Konto erstellen',
      validation: {
        confirmPasswordRequired: 'Bestätigen Sie Ihr Passwort.',
        emailInvalid: 'Geben Sie eine gültige E-Mail-Adresse ein.',
        emailRequired: 'E-Mail ist erforderlich.',
        fullNameMax: 'Der vollständige Name darf höchstens 80 Zeichen enthalten.',
        fullNameMin: 'Der vollständige Name muss mindestens 2 Zeichen enthalten.',
        fullNameRequired: 'Der vollständige Name ist erforderlich.',
        passwordMax: 'Das Passwort darf höchstens 128 Zeichen enthalten.',
        passwordMin: 'Das Passwort muss mindestens 8 Zeichen enthalten.',
        passwordRequired: 'Das Passwort ist erforderlich.',
        passwordsMismatch: 'Die Passwörter stimmen nicht überein.',
      },
    },
    registrationVerification: {
      accountAlreadyExists: 'Ein Konto mit dieser E-Mail existiert bereits. Kehren Sie zur Anmeldung zurück.',
      codeAccessibilityLabel: 'Sechsstelliger Bestätigungscode für die Registrierung',
      codeResent: 'Neuer Bestätigungscode gesendet',
      confirm: 'E-Mail bestätigen',
      correctDetails: 'Registrierungsdaten korrigieren',
      description: 'Geben Sie den sechsstelligen Code ein, den wir an Ihre E-Mail gesendet haben.',
      emailDestination: 'Code gesendet an {{email}}',
      expiredRegistration: 'Diese Registrierung ist abgelaufen. Kehren Sie zurück und erstellen Sie Ihr Konto erneut.',
      genericError: 'Ihre E-Mail konnte nicht bestätigt werden. Bitte versuchen Sie es erneut.',
      invalidCode: 'Der Bestätigungscode ist ungültig oder abgelaufen.',
      invalidCodeFormat: 'Geben Sie genau sechs Ziffern ein.',
      networkError: 'Keine Internetverbindung. Prüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
      rateLimited: 'Zu viele Versuche. Bitte warten Sie vor dem nächsten Versuch.',
      resend: 'Code erneut senden',
      resendIn: 'Code erneut senden in {{time}}',
      serverUnavailable: 'Der Server ist vorübergehend nicht verfügbar. Bitte versuchen Sie es später erneut.',
      timeoutError: 'Die Anfrage hat zu lange gedauert. Bitte versuchen Sie es erneut.',
      title: 'E-Mail bestätigen',
    },
    otp: {
      codeAccessibilityLabel: 'Sechsstelliger Bestätigungscode zur Passwortwiederherstellung',
      codeResent: 'Falls ein Konto für diese E-Mail existiert, wurde ein neuer Code gesendet.',
      codeSentTo: 'Code gesendet an {{email}}',
      explanation: 'Geben Sie den sechsstelligen Code aus Ihrer E-Mail ein.',
      invalidCodeFormat: 'Geben Sie genau sechs Ziffern ein.',
      resendCode: 'Code erneut senden',
      resendIn: 'Erneut senden in {{seconds}} s',
      title: 'Bestätigungscode eingeben',
    },
    recovery: {
      back: 'Zurück',
      backToLogin: 'Zurück zur Anmeldung',
      invalidOrExpiredCode: 'Der Bestätigungscode ist ungültig oder abgelaufen.',
      networkError: 'Keine Internetverbindung. Prüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
      rateLimited: 'Zu viele Anfragen. Bitte warten Sie vor dem nächsten Versuch.',
      serverUnavailable: 'Der Server ist vorübergehend nicht verfügbar. Versuchen Sie es später erneut.',
      timeoutError: 'Die Zeitüberschreitung für die Anfrage wurde erreicht.',
      tooManyAttempts: 'Zu viele fehlgeschlagene Versuche. Fordern Sie einen neuen Code an.',
      usedCode: 'Dieser Code wurde bereits verwendet. Fordern Sie einen neuen an.',
    },
    resetPassword: {
      confirmNewPassword: 'Neues Passwort bestätigen',
      explanation: 'Wählen Sie ein neues Passwort für Ihr FastRep-Konto.',
      newPassword: 'Neues Passwort',
      resetPassword: 'Passwort zurücksetzen',
      success: 'Passwort geändert',
      title: 'Passwort zurücksetzen',
      validation: {
        confirmPasswordRequired: 'Bestätigen Sie Ihr neues Passwort.',
        passwordMax: 'Das Passwort darf höchstens 128 Zeichen enthalten.',
        passwordMin: 'Das Passwort muss mindestens 8 Zeichen enthalten.',
        passwordRequired: 'Das Passwort ist erforderlich.',
        passwordsMismatch: 'Die Passwörter stimmen nicht überein.',
      },
    },
    session: {
      expired: 'Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut an.',
      genericError: 'Die Authentifizierung konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.',
      networkUnavailable: 'Keine Internetverbindung. Prüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
      restoring: 'Ihre Sitzung wird wiederhergestellt…',
      serverError: 'Der Server ist vorübergehend nicht verfügbar. Bitte versuchen Sie es später erneut.',
      timeout: 'Die Zeitüberschreitung für die Anfrage wurde erreicht. Bitte versuchen Sie es erneut.',
    },
  },
  common: {
    back: 'Zurück',
    cancel: 'Abbrechen',
    close: 'Schließen',
    continue: 'Weiter',
    error: 'Fehler',
    info: 'Information',
    loading: 'Wird geladen',
    no: 'Nein',
    retry: 'Erneut versuchen',
    save: 'Speichern',
    somethingWentWrong: 'Etwas ist schiefgelaufen',
    success: 'Erfolg',
    yes: 'Ja',
  },
  profile: {
    environment: {
      confirmationMessage: 'Sie werden abgemeldet und mit der Umgebung {{environment}} verbunden.',
      confirmationTitle: 'Umgebung wechseln?',
      developmentIndicator: 'Entwicklungsumgebung',
      selectionMessage: 'Wählen Sie die API-Umgebung für Ihre nächste Sitzung.',
      switchAction: 'Wechseln',
      title: 'Umgebung',
    },
    logout: 'Abmelden',
    logoutError: 'Sie wurden auf diesem Gerät abgemeldet, der Server konnte jedoch nicht benachrichtigt werden.',
    title: 'Profil',
  },
  reports: {
    attachments: {
      audio: 'Audio', camera: 'Kamera', cameraPermission: 'Erlaube den Kamerazugriff, um ein Foto aufzunehmen.', confirmFailed: 'Anhang konnte nicht geprüft werden', empty: 'Noch keine Anhänge', file: 'Datei', invalid: 'Anhang wird nicht unterstützt', microphonePermission: 'Erlaube den Mikrofonzugriff für Audioaufnahmen.', permissionTitle: 'Berechtigung erforderlich', photo: 'Foto', photoFailed: 'Foto konnte nicht hinzugefügt werden', recording: 'Aufnahme · {{duration}}', recordingFailed: 'Audio konnte nicht aufgenommen werden', remove: 'Entfernen', removeFailed: 'Anhang konnte nicht entfernt werden',
      states: { CONFIRMING: 'Prüfen', FAILED: 'Upload fehlgeschlagen', LOCAL: 'Warten', READY: 'Bereit', REQUESTING_UPLOAD: 'Vorbereiten', UPLOADING: 'Hochladen' }, stop: 'Stoppen', title: 'Anhänge', tryAgain: 'Versuche es erneut.', types: { AUDIO: 'Audio', DOCUMENT: 'Datei', IMAGE: 'Foto' }, uploadFailed: 'Upload des Anhangs fehlgeschlagen',
      validation: { audioDurationTooLong: 'Audioaufnahmen dürfen bis zu 20 Minuten lang sein.', fileTooLarge: 'Diese Datei ist zu groß.', imageDimensionsTooLarge: 'Bilder dürfen höchstens 4096 × 4096 Pixel groß sein.', missingFileMetadata: 'Die ausgewählte Datei konnte nicht gelesen werden.', reportTotalTooLarge: 'Anhänge eines Berichts dürfen insgesamt 150 MB groß sein.', tooManyFiles: 'Das Limit für diesen Anhangstyp ist erreicht.', unsupportedType: 'Wähle ein unterstütztes Dateiformat.' },
    },
    card: {
      created: 'Erstellt {{date}}',
      updated: 'Aktualisiert {{date}}',
    },
    create: {
      action: 'Bericht erstellen',
      success: 'Bericht erstellt',
      title: 'Bericht erstellen',
    },
    delete: {
      action: 'Löschen',
      alreadyDeleted: 'Bericht wurde bereits gelöscht.',
      confirmation: 'Diese Aktion kann nicht rückgängig gemacht werden. Der Bericht wird dauerhaft gelöscht.',
      success: 'Bericht gelöscht',
      title: 'Bericht löschen?',
    },
    details: {
      createdAt: 'Erstellt',
      errorDescription: 'Dieser Bericht konnte nicht geladen werden. Bitte erneut versuchen.',
      errorTitle: 'Bericht kann nicht geladen werden',
      noNotes: 'Keine Notizen',
      notFoundDescription: 'Dieser Bericht wurde möglicherweise gelöscht oder ist nicht mehr verfügbar.',
      notFoundTitle: 'Bericht nicht gefunden',
      title: 'Berichtsdetails',
      updatedAt: 'Aktualisiert',
    },
    edit: {
      action: 'Bearbeiten',
      success: 'Bericht aktualisiert',
      title: 'Bericht bearbeiten',
    },
    errors: {
      network: 'Keine Internetverbindung. Verbindung prüfen und erneut versuchen.',
      notFound: 'Der Bericht wurde nicht gefunden.',
      server: 'Der Server ist vorübergehend nicht verfügbar. Bitte später erneut versuchen.',
      timeout: 'Die Anfrage hat zu lange gedauert. Bitte erneut versuchen.',
      validation: 'Berichtsdaten prüfen und erneut versuchen.',
    },
    form: {
      notes: 'Notizen',
      notesPlaceholder: 'Nützliche Details hinzufügen',
      title: 'Titel',
      titlePlaceholder: 'Berichtstitel',
    },
    generation: {
      cancel: 'Generierung abbrechen', cancelFailed: 'Generierung konnte nicht abgebrochen werden', credits: '{{count}} Credits',
      errors: { GENERATION_ALREADY_ACTIVE: 'Für diesen Bericht läuft bereits eine Generierung.', GENERATION_CREDITS_EXHAUSTED: 'Keine Generierungs-Credits verfügbar.', GENERATION_CREDIT_RESERVATION_FAILED: 'Ein Credit konnte nicht reserviert werden. Versuche es erneut.', GENERATION_DAILY_LIMIT_REACHED: 'Das tägliche Generierungslimit ist erreicht.', GENERATION_DISABLED: 'Die Berichtsgenerierung ist vorübergehend nicht verfügbar.', GENERATION_QUEUE_UNAVAILABLE: 'Der Generierungsdienst ist vorübergehend nicht verfügbar.', GENERATION_RATE_LIMITED: 'Zu viele Anfragen. Warte kurz und versuche es erneut.', REPORT_HAS_NO_CONTENT: 'Füge zuerst Notizen oder einen Anhang hinzu.', REPORT_HAS_PENDING_UPLOADS: 'Warte, bis alle Anhänge hochgeladen sind.', REPORT_HAS_REJECTED_ASSETS: 'Entferne abgelehnte Anhänge.', REPORT_NOT_EDITABLE: 'Dieser Bericht kann in seinem aktuellen Zustand nicht generiert werden.', REPORT_TEMPORARILY_LOCKED: 'Dieser Bericht ist nach wiederholten Fehlern vorübergehend gesperrt.', generic: 'Der Bericht konnte nicht generiert werden. Versuche es erneut.' },
      failedDescription: 'Die Generierung ist fehlgeschlagen. Bearbeite die Quellen und versuche es erneut.', generate: 'Bericht generieren', generated: 'Bericht generiert', lock: { message: 'Dieser Bericht ist mehrfach fehlgeschlagen. Versuche es in {{minutes}} Minuten erneut.', title: 'Bericht vorübergehend nicht verfügbar' }, regenerate: 'Neu generieren', retry: 'Generierung wiederholen', stages: { analyzing: 'Anhänge analysieren…', completed: 'Abgeschlossen', creatingPdf: 'PDF erstellen…', finalizing: 'Abschließen…', generating: 'Bericht generieren…', preparing: 'Vorbereiten…', transcribing: 'Audio transkribieren…' }, startFailed: 'Generierung fehlgeschlagen', title: 'KI-Bericht',
    },
    list: {
      emptyDescription: 'Erstellen Sie Ihren ersten Bericht, um Fortschritt und Notizen an einem Ort zu verwalten.',
      emptyTitle: 'Noch keine Berichte',
      errorDescription: 'Ihre Berichte konnten nicht geladen werden. Verbindung prüfen und erneut versuchen.',
      errorTitle: 'Berichte können nicht geladen werden',
      title: 'Berichte',
    },
    output: { open: 'Bericht öffnen', openFailed: 'Bericht konnte nicht geöffnet werden', share: 'Bericht teilen', shareFailed: 'Bericht konnte nicht geteilt werden', tryAgain: 'Lade das PDF erneut und versuche es noch einmal.' },
    status: {
      draft: 'Entwurf',
      failed: 'Fehlgeschlagen',
      processing: 'In Bearbeitung',
      ready: 'Bereit',
    },
    validation: {
      notesMax: 'Notizen dürfen höchstens 50.000 Zeichen enthalten.',
      titleMax: 'Der Titel darf höchstens 120 Zeichen enthalten.',
      titleRequired: 'Der Titel ist erforderlich.',
    },
  },
  languages: {
    english: 'Englisch',
    french: 'Französisch',
    german: 'Deutsch',
    spanish: 'Spanisch',
    ukrainian: 'Ukrainisch',
  },
  showcase: {
    currentLanguage: 'Aktuelle Sprache',
    description: 'Demo der wiederverwendbaren Anwendungsgrundlage',
    showError: 'Fehler anzeigen',
    showSuccess: 'Erfolg anzeigen',
    successMessage: 'Zweizeilige Erfolgsmeldungen bieten Platz für zusätzliche Details.',
    successTitle: 'Änderungen gespeichert',
    title: 'FastRep Grundlage',
  },
};
