import type { TranslationResources } from './types';

export const de: TranslationResources = {
  auth: {
    forgotPassword: {
      codeSent: 'Falls ein Konto für diese E-Mail existiert, wurde ein Bestätigungscode gesendet.',
      email: 'E-Mail',
      explanation: 'Geben Sie Ihre E-Mail ein, um einen sechsstelligen Bestätigungscode zu erhalten.',
      sendCode: 'Code senden',
      title: 'Passwort vergessen',
      validation: {
        emailInvalid: 'Geben Sie eine gültige E-Mail-Adresse ein.',
        emailRequired: 'E-Mail ist erforderlich.',
      },
    },
    login: {
      createAccount: 'Konto erstellen',
      description: 'Melden Sie sich an, um FastRep weiter zu nutzen.',
      email: 'E-Mail',
      forgotPassword: 'Passwort vergessen?',
      invalidCredentials: 'Die E-Mail-Adresse oder das Passwort ist falsch.',
      logIn: 'Anmelden',
      password: 'Passwort',
      title: 'Willkommen zurück',
      validation: {
        emailInvalid: 'Geben Sie eine gültige E-Mail-Adresse ein.',
        emailRequired: 'E-Mail ist erforderlich.',
        passwordMax: 'Das Passwort darf höchstens 128 Zeichen enthalten.',
        passwordMin: 'Das Passwort muss mindestens 8 Zeichen enthalten.',
        passwordRequired: 'Das Passwort ist erforderlich.',
      },
    },
    registration: {
      alreadyHaveAccount: 'Sie haben bereits ein Konto?',
      confirmPassword: 'Passwort bestätigen',
      createAccount: 'Konto erstellen',
      email: 'E-Mail',
      fullName: 'Vollständiger Name',
      logIn: 'Anmelden',
      password: 'Passwort',
      subtitle: 'Erstellen Sie Ihr FastRep-Konto, um loszulegen.',
      title: 'Konto erstellen',
      validation: {
        confirmPasswordRequired: 'Bestätigen Sie Ihr Passwort.',
        emailInvalid: 'Geben Sie eine gültige E-Mail-Adresse ein.',
        emailRequired: 'E-Mail ist erforderlich.',
        fullNameMax: 'Der vollständige Name darf höchstens 80 Zeichen enthalten.',
        fullNameMin: 'Der vollständige Name muss mindestens 2 Zeichen enthalten.',
        fullNameRequired: 'Der vollständige Name ist erforderlich.',
        passwordMax: 'Das Passwort darf höchstens 128 Zeichen enthalten.',
        passwordMin: 'Das Passwort muss mindestens 8 Zeichen enthalten.',
        passwordRequired: 'Das Passwort ist erforderlich.',
        passwordsMismatch: 'Die Passwörter stimmen nicht überein.',
      },
    },
    registrationVerification: {
      accountAlreadyExists: 'Ein Konto mit dieser E-Mail existiert bereits. Kehren Sie zur Anmeldung zurück.',
      codeAccessibilityLabel: 'Sechsstelliger Bestätigungscode für die Registrierung',
      codeResent: 'Ein neuer Bestätigungscode wurde gesendet.',
      confirm: 'E-Mail bestätigen',
      correctDetails: 'Registrierungsdaten korrigieren',
      description: 'Geben Sie den sechsstelligen Code ein, den wir an Ihre E-Mail gesendet haben.',
      emailDestination: 'Code gesendet an {{email}}',
      expiredRegistration: 'Diese Registrierung ist abgelaufen. Kehren Sie zurück und erstellen Sie Ihr Konto erneut.',
      genericError: 'Ihre E-Mail konnte nicht bestätigt werden. Bitte versuchen Sie es erneut.',
      invalidCode: 'Der Bestätigungscode ist ungültig oder abgelaufen.',
      invalidCodeFormat: 'Geben Sie genau sechs Ziffern ein.',
      networkError: 'Keine Internetverbindung. Prüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
      rateLimited: 'Zu viele Versuche. Bitte warten Sie vor dem nächsten Versuch.',
      resend: 'Code erneut senden',
      resendIn: 'Code erneut senden in {{time}}',
      serverUnavailable: 'Der Server ist vorübergehend nicht verfügbar. Bitte versuchen Sie es später erneut.',
      timeoutError: 'Die Anfrage hat zu lange gedauert. Bitte versuchen Sie es erneut.',
      title: 'E-Mail bestätigen',
    },
    otp: {
      codeAccessibilityLabel: 'Sechsstelliger Bestätigungscode zur Passwortwiederherstellung',
      codeResent: 'Falls ein Konto für diese E-Mail existiert, wurde ein neuer Code gesendet.',
      codeSentTo: 'Code gesendet an {{email}}',
      explanation: 'Geben Sie den sechsstelligen Code aus Ihrer E-Mail ein.',
      invalidCodeFormat: 'Geben Sie genau sechs Ziffern ein.',
      resendCode: 'Code erneut senden',
      resendIn: 'Erneut senden in {{seconds}} s',
      title: 'Bestätigungscode eingeben',
    },
    recovery: {
      back: 'Zurück',
      backToLogin: 'Zurück zur Anmeldung',
      invalidOrExpiredCode: 'Der Bestätigungscode ist ungültig oder abgelaufen.',
      networkError: 'Keine Internetverbindung. Prüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
      rateLimited: 'Zu viele Anfragen. Bitte warten Sie vor dem nächsten Versuch.',
      serverUnavailable: 'Der Server ist vorübergehend nicht verfügbar. Versuchen Sie es später erneut.',
      timeoutError: 'Die Zeitüberschreitung für die Anfrage wurde erreicht.',
      tooManyAttempts: 'Zu viele fehlgeschlagene Versuche. Fordern Sie einen neuen Code an.',
      usedCode: 'Dieser Code wurde bereits verwendet. Fordern Sie einen neuen an.',
    },
    resetPassword: {
      confirmNewPassword: 'Neues Passwort bestätigen',
      explanation: 'Wählen Sie ein neues Passwort für Ihr FastRep-Konto.',
      newPassword: 'Neues Passwort',
      resetPassword: 'Passwort zurücksetzen',
      success: 'Ihr Passwort wurde zurückgesetzt. Melden Sie sich mit dem neuen Passwort an.',
      title: 'Passwort zurücksetzen',
      validation: {
        confirmPasswordRequired: 'Bestätigen Sie Ihr neues Passwort.',
        passwordMax: 'Das Passwort darf höchstens 128 Zeichen enthalten.',
        passwordMin: 'Das Passwort muss mindestens 8 Zeichen enthalten.',
        passwordRequired: 'Das Passwort ist erforderlich.',
        passwordsMismatch: 'Die Passwörter stimmen nicht überein.',
      },
    },
    session: {
      expired: 'Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut an.',
      genericError: 'Die Authentifizierung konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.',
      networkUnavailable: 'Keine Internetverbindung. Prüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
      restoring: 'Ihre Sitzung wird wiederhergestellt…',
      serverError: 'Der Server ist vorübergehend nicht verfügbar. Bitte versuchen Sie es später erneut.',
      timeout: 'Die Zeitüberschreitung für die Anfrage wurde erreicht. Bitte versuchen Sie es erneut.',
    },
  },
  common: {
    back: 'Zurück',
    cancel: 'Abbrechen',
    close: 'Schließen',
    continue: 'Weiter',
    error: 'Fehler',
    info: 'Information',
    loading: 'Wird geladen',
    no: 'Nein',
    retry: 'Erneut versuchen',
    save: 'Speichern',
    somethingWentWrong: 'Etwas ist schiefgelaufen',
    success: 'Erfolg',
    yes: 'Ja',
  },
  profile: {
    logout: 'Abmelden',
    logoutError: 'Sie wurden auf diesem Gerät abgemeldet, der Server konnte jedoch nicht benachrichtigt werden.',
    title: 'Profil',
  },
  reports: {
    card: {
      created: 'Erstellt {{date}}',
      updated: 'Aktualisiert {{date}}',
    },
    create: {
      action: 'Bericht erstellen',
      success: 'Bericht erfolgreich erstellt.',
      title: 'Bericht erstellen',
    },
    delete: {
      action: 'Löschen',
      alreadyDeleted: 'Bericht wurde bereits gelöscht.',
      confirmation: 'Diese Aktion kann nicht rückgängig gemacht werden. Der Bericht wird dauerhaft gelöscht.',
      success: 'Bericht erfolgreich gelöscht.',
      title: 'Bericht löschen?',
    },
    details: {
      createdAt: 'Erstellt',
      errorDescription: 'Dieser Bericht konnte nicht geladen werden. Bitte erneut versuchen.',
      errorTitle: 'Bericht kann nicht geladen werden',
      noNotes: 'Keine Notizen',
      notFoundDescription: 'Dieser Bericht wurde möglicherweise gelöscht oder ist nicht mehr verfügbar.',
      notFoundTitle: 'Bericht nicht gefunden',
      title: 'Berichtsdetails',
      updatedAt: 'Aktualisiert',
    },
    edit: {
      action: 'Bearbeiten',
      success: 'Bericht erfolgreich aktualisiert.',
      title: 'Bericht bearbeiten',
    },
    errors: {
      network: 'Keine Internetverbindung. Verbindung prüfen und erneut versuchen.',
      notFound: 'Der Bericht wurde nicht gefunden.',
      server: 'Der Server ist vorübergehend nicht verfügbar. Bitte später erneut versuchen.',
      timeout: 'Die Anfrage hat zu lange gedauert. Bitte erneut versuchen.',
      validation: 'Berichtsdaten prüfen und erneut versuchen.',
    },
    form: {
      notes: 'Notizen',
      notesPlaceholder: 'Nützliche Details hinzufügen',
      title: 'Titel',
      titlePlaceholder: 'Berichtstitel',
    },
    list: {
      emptyDescription: 'Erstellen Sie Ihren ersten Bericht, um Fortschritt und Notizen an einem Ort zu verwalten.',
      emptyTitle: 'Noch keine Berichte',
      errorDescription: 'Ihre Berichte konnten nicht geladen werden. Verbindung prüfen und erneut versuchen.',
      errorTitle: 'Berichte können nicht geladen werden',
      title: 'Berichte',
    },
    status: {
      draft: 'Entwurf',
      failed: 'Fehlgeschlagen',
      processing: 'In Bearbeitung',
      ready: 'Bereit',
    },
    validation: {
      notesMax: 'Notizen dürfen höchstens 50.000 Zeichen enthalten.',
      titleMax: 'Der Titel darf höchstens 120 Zeichen enthalten.',
      titleRequired: 'Der Titel ist erforderlich.',
    },
  },
  languages: {
    english: 'Englisch',
    french: 'Französisch',
    german: 'Deutsch',
    spanish: 'Spanisch',
    ukrainian: 'Ukrainisch',
  },
  showcase: {
    currentLanguage: 'Aktuelle Sprache',
    description: 'Demo der wiederverwendbaren Anwendungsgrundlage',
    showError: 'Fehler anzeigen',
    showSuccess: 'Erfolg anzeigen',
    title: 'FastRep Grundlage',
  },
};
