import type { TranslationResources } from './types';

export const en: TranslationResources = {
  auth: {
    environment: {
      productionRequired: 'This account can only use the Production environment. Please log in again.',
    },
    forgotPassword: {
      codeSent: 'Verification code sent',
      email: 'Email',
      explanation: 'Enter your email address and we will send you a six-digit verification code.',
      sendCode: 'Send code',
      title: 'Forgot password',
      validation: {
        emailInvalid: 'Enter a valid email address.',
        emailRequired: 'Email is required.',
      },
    },
    login: {
      createAccount: 'Create account',
      description: 'Log in to continue using FastRep.',
      email: 'Email',
      forgotPassword: 'Forgot password?',
      invalidCredentials: 'The email or password is incorrect.',
      logIn: 'Log in',
      password: 'Password',
      title: 'Welcome back',
      validation: {
        emailInvalid: 'Enter a valid email address.',
        emailRequired: 'Email is required.',
        passwordMax: 'Password must contain no more than 128 characters.',
        passwordMin: 'Password must contain at least 8 characters.',
        passwordRequired: 'Password is required.',
      },
    },
    registration: {
      alreadyHaveAccount: 'Already have an account?',
      confirmPassword: 'Confirm password',
      createAccount: 'Create account',
      email: 'Email',
      fullName: 'Full name',
      logIn: 'Log in',
      password: 'Password',
      subtitle: 'Create your FastRep account to get started.',
      title: 'Create your account',
      validation: {
        confirmPasswordRequired: 'Confirm your password.',
        emailInvalid: 'Enter a valid email address.',
        emailRequired: 'Email is required.',
        fullNameMax: 'Full name must be no more than 80 characters.',
        fullNameMin: 'Full name must contain at least 2 characters.',
        fullNameRequired: 'Full name is required.',
        passwordMax: 'Password must contain no more than 128 characters.',
        passwordMin: 'Password must contain at least 8 characters.',
        passwordRequired: 'Password is required.',
        passwordsMismatch: 'Passwords do not match.',
      },
    },
    registrationVerification: {
      accountAlreadyExists: 'An account with this email already exists. Return to log in.',
      codeAccessibilityLabel: 'Six-digit registration verification code',
      codeResent: 'New verification code sent',
      confirm: 'Confirm email',
      correctDetails: 'Correct registration details',
      description: 'Enter the six-digit code we sent to your email.',
      emailDestination: 'Code sent to {{email}}',
      expiredRegistration: 'This registration has expired. Return and create your account again.',
      genericError: "We couldn't verify your email. Please try again.",
      invalidCode: 'The verification code is invalid or expired.',
      invalidCodeFormat: 'Enter exactly six digits.',
      networkError: 'No internet connection. Check your connection and try again.',
      rateLimited: 'Too many attempts. Please wait before trying again.',
      resend: 'Resend code',
      resendIn: 'Resend code in {{time}}',
      serverUnavailable: 'The server is temporarily unavailable. Please try again later.',
      timeoutError: 'The request timed out. Please try again.',
      title: 'Verify your email',
    },
    otp: {
      codeAccessibilityLabel: 'Six-digit password recovery verification code',
      codeResent: 'New verification code sent',
      codeSentTo: 'Code sent to {{email}}',
      explanation: 'Enter the six-digit code from your email.',
      invalidCodeFormat: 'Enter exactly six digits.',
      resendCode: 'Resend code',
      resendIn: 'Resend in {{seconds}}s',
      title: 'Enter verification code',
    },
    recovery: {
      back: 'Back',
      backToLogin: 'Back to login',
      invalidOrExpiredCode: 'The verification code is invalid or expired.',
      networkError: 'No internet connection. Check your connection and try again.',
      rateLimited: 'Too many requests. Please wait before trying again.',
      serverUnavailable: 'The server is temporarily unavailable. Please try again later.',
      timeoutError: 'The request timed out. Please try again.',
      tooManyAttempts: 'Too many unsuccessful attempts. Request a new verification code.',
      usedCode: 'This verification code has already been used. Request a new code.',
    },
    resetPassword: {
      confirmNewPassword: 'Confirm new password',
      explanation: 'Choose a new password for your FastRep account.',
      newPassword: 'New password',
      resetPassword: 'Reset password',
      success: 'Password changed',
      title: 'Reset password',
      validation: {
        confirmPasswordRequired: 'Confirm your new password.',
        passwordMax: 'Password must contain no more than 128 characters.',
        passwordMin: 'Password must contain at least 8 characters.',
        passwordRequired: 'Password is required.',
        passwordsMismatch: 'Passwords do not match.',
      },
    },
    session: {
      expired: 'Your session has expired. Please log in again.',
      genericError: "We couldn't complete authentication. Please try again.",
      networkUnavailable: 'No internet connection. Check your connection and try again.',
      restoring: 'Restoring your session…',
      serverError: 'The server is temporarily unavailable. Please try again later.',
      timeout: 'The request timed out. Please try again.',
    },
  },
  common: {
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    continue: 'Continue',
    error: 'Error',
    info: 'Info',
    loading: 'Loading',
    no: 'No',
    retry: 'Retry',
    save: 'Save',
    somethingWentWrong: 'Something went wrong',
    success: 'Success',
    yes: 'Yes',
  },
  profile: {
    environment: {
      confirmationMessage: 'You will be signed out and connected to the {{environment}} environment.',
      confirmationTitle: 'Switch environment?',
      developmentIndicator: 'Development environment',
      selectionMessage: 'Choose the API environment for your next session.',
      switchAction: 'Switch',
      title: 'Environment',
    },
    logout: 'Log out',
    logoutError: "You were logged out on this device, but we couldn't notify the server.",
    title: 'Profile',
  },
  reports: {
    attachments: {
      accessFailed: 'Could not open attachment',
      attentionRequired: 'Attachment needs attention',
      audioRecordingName: 'Audio recording',
      delete: 'Remove',
      deleteAccessibility: 'Delete {{name}}',
      deleteConfirmation: 'This file will no longer be included in future report generations.',
      deleteTitle: 'Remove attachment?',
      fileName: 'File',
      pauseAccessibility: 'Pause {{name}}',
      photoName: 'Photo',
      playFailed: 'Could not play audio',
      playAccessibility: 'Play {{name}}',
      rejectionReasons: {
        expired: 'The upload expired. Add this attachment again.',
        invalidContent: 'The file contents could not be processed.',
        limitExceeded: 'The attachment limit was exceeded.',
        processingFailed: 'This attachment could not be processed.',
        storageUnavailable: 'Storage was temporarily unavailable.',
        tooLarge: 'This attachment is too large.',
        unsupportedType: 'This file type is not supported.',
      },
      removed: 'Attachment deleted',
      retryAccessibility: 'Retry {{name}}',
      audio: 'Audio', camera: 'Camera', cameraPermission: 'Allow camera access to take a photo.',
      confirmFailed: 'Could not verify attachment', documentFailed: 'Could not add file', empty: 'No attachments yet', file: 'File',
      invalid: 'Attachment not supported', microphonePermission: 'Allow microphone access to record audio.',
      permissionTitle: 'Permission required', photo: 'Photo', photoConversionFailed: 'Could not convert this photo to a supported format', photoFailed: 'Could not add photo',
      recording: 'Recording · {{duration}}', recordingFailed: 'Could not record audio', remove: 'Remove',
      removeFailed: 'Could not remove attachment',
      states: { CONFIRMING: 'Verifying', FAILED: 'Upload failed', LOCAL: 'Waiting', READY: 'Ready', REQUESTING_UPLOAD: 'Preparing', UPLOADING: 'Uploading' },
      stop: 'Stop', title: 'Attachments', tryAgain: 'Try again.',
      types: { AUDIO: 'Audio', DOCUMENT: 'File', IMAGE: 'Photo' }, uploadFailed: 'Attachment upload failed',
      validation: {
        audioDurationTooLong: 'Audio recordings can be up to 20 minutes.', fileTooLarge: 'This file is too large.',
        imageDimensionsTooLarge: 'Images can be up to 4096 × 4096 pixels.', missingFileMetadata: 'The selected file could not be read.',
        reportTotalTooLarge: 'Attachments for one report can total up to 150 MB.', tooManyFiles: 'This report has reached the limit for this attachment type.',
        unsupportedType: 'Choose a supported file format.',
      },
    },
    fallbackTitle: 'New report',
    card: {
      created: 'Created {{date}}',
      updated: 'Updated {{date}}',
    },
    create: {
      action: 'Create report',
      success: 'Report created',
      title: 'Create report',
    },
    delete: {
      action: 'Delete',
      alreadyDeleted: 'Report was already deleted.',
      confirmation: 'This action cannot be undone. The report will be permanently deleted.',
      success: 'Report deleted',
      title: 'Delete report?',
    },
    details: {
      createdAt: 'Created',
      errorDescription: 'We could not load this report. Please try again.',
      errorTitle: 'Unable to load report',
      noNotes: 'No notes',
      notFoundDescription: 'This report may have been deleted or is no longer available.',
      notFoundTitle: 'Report not found',
      title: 'Report details',
      updatedAt: 'Updated',
    },
    edit: {
      action: 'Edit',
      success: 'Report updated',
      title: 'Edit report',
    },
    errors: {
      network: 'No internet connection. Check your connection and try again.',
      notFound: 'The report was not found.',
      server: 'The server is temporarily unavailable. Please try again later.',
      timeout: 'The request timed out. Please try again.',
      validation: 'Check the report details and try again.',
    },
    form: {
      notes: 'Notes',
      notesPlaceholder: 'Add any useful details',
      title: 'Title',
      titlePlaceholder: 'Report title',
    },
    generation: {
      cancel: 'Cancel generation', cancelFailed: 'Could not cancel generation', credits: '{{count}} credits', description: 'Turn your notes and attachments into a polished PDF report.',
      rejectedAttachments: 'Retry or delete the marked attachment before generating the report.',
      errors: {
        GENERATION_ALREADY_ACTIVE: 'A generation is already running for this report.', GENERATION_CREDITS_EXHAUSTED: 'You have no generation credits available.',
        GENERATION_CREDIT_RESERVATION_FAILED: 'A generation credit could not be reserved. Try again.', GENERATION_DAILY_LIMIT_REACHED: 'The daily generation limit has been reached.',
        GENERATION_DISABLED: 'Report generation is temporarily unavailable.', GENERATION_QUEUE_UNAVAILABLE: 'The generation service is temporarily unavailable.',
        GENERATION_RATE_LIMITED: 'Too many requests. Wait a moment and try again.', REPORT_HAS_NO_CONTENT: 'Add notes or at least one attachment first.',
        REPORT_HAS_PENDING_UPLOADS: 'Wait for every attachment to finish uploading.', REPORT_HAS_REJECTED_ASSETS: 'Remove rejected attachments before generating.',
        REPORT_NOT_EDITABLE: 'This report cannot be generated in its current state.', REPORT_TEMPORARILY_LOCKED: 'This report is temporarily unavailable after repeated failures.',
        generic: 'The report could not be generated. Try again.',
      },
      failedDescription: 'Generation failed. You can edit the sources and try again.', generate: 'Generate report', generated: 'Report generated',
      lock: { message: 'This report failed several times. Try again in {{minutes}} minutes.', title: 'Report temporarily unavailable' }, outputReady: 'Your report is ready',
      regenerate: 'Regenerate', retry: 'Retry generation',
      stages: { analyzing: 'Analyzing attachments…', completed: 'Completed', creatingPdf: 'Creating PDF…', finalizing: 'Finalizing…', generating: 'Generating report…', preparing: 'Preparing…', transcribing: 'Transcribing audio…' },
      startFailed: 'Generation failed', title: 'AI report',
    },
    list: {
      emptyDescription: 'Create your first report to keep its progress and notes in one place.',
      emptyTitle: 'No reports yet',
      errorDescription: 'We could not load your reports. Check your connection and try again.',
      errorTitle: 'Unable to load reports',
      title: 'Reports',
    },
    output: { open: 'Open report', openFailed: 'Could not open report', share: 'Share report', shareFailed: 'Could not share report', tryAgain: 'Download the PDF again and retry.' },
    status: {
      draft: 'Draft',
      failed: 'Failed',
      processing: 'Processing',
      ready: 'Ready',
    },
    validation: {
      notesMax: 'Notes must contain no more than 50,000 characters.',
      titleMax: 'Title must contain no more than 120 characters.',
      titleRequired: 'Title is required.',
    },
  },
  languages: {
    english: 'English',
    french: 'French',
    german: 'German',
    spanish: 'Spanish',
    ukrainian: 'Ukrainian',
  },
  showcase: {
    currentLanguage: 'Current language',
    description: 'Reusable application foundation showcase',
    showError: 'Show error',
    showSuccess: 'Show success',
    successMessage: 'Two-line success toasts remain available for additional details.',
    successTitle: 'Changes saved',
    title: 'FastRep Foundation',
  },
};
