import type { TranslationResources } from './types';

export const en: TranslationResources = {
  auth: {
    forgotPassword: {
      codeSent: 'If an account exists for this email, we sent a verification code.',
      email: 'Email',
      explanation: 'Enter your email address and we will send you a six-digit verification code.',
      sendCode: 'Send code',
      title: 'Forgot password',
      validation: {
        emailInvalid: 'Enter a valid email address.',
        emailRequired: 'Email is required.',
      },
    },
    login: {
      createAccount: 'Create account',
      description: 'Log in to continue using FastRep.',
      email: 'Email',
      forgotPassword: 'Forgot password?',
      invalidCredentials: 'The email or password is incorrect.',
      logIn: 'Log in',
      password: 'Password',
      title: 'Welcome back',
      validation: {
        emailInvalid: 'Enter a valid email address.',
        emailRequired: 'Email is required.',
        passwordMax: 'Password must contain no more than 128 characters.',
        passwordMin: 'Password must contain at least 8 characters.',
        passwordRequired: 'Password is required.',
      },
    },
    registration: {
      alreadyHaveAccount: 'Already have an account?',
      confirmPassword: 'Confirm password',
      createAccount: 'Create account',
      email: 'Email',
      fullName: 'Full name',
      logIn: 'Log in',
      password: 'Password',
      subtitle: 'Create your FastRep account to get started.',
      title: 'Create your account',
      validation: {
        confirmPasswordRequired: 'Confirm your password.',
        emailInvalid: 'Enter a valid email address.',
        emailRequired: 'Email is required.',
        fullNameMax: 'Full name must be no more than 80 characters.',
        fullNameMin: 'Full name must contain at least 2 characters.',
        fullNameRequired: 'Full name is required.',
        passwordMax: 'Password must contain no more than 128 characters.',
        passwordMin: 'Password must contain at least 8 characters.',
        passwordRequired: 'Password is required.',
        passwordsMismatch: 'Passwords do not match.',
      },
    },
    registrationVerification: {
      accountAlreadyExists: 'An account with this email already exists. Return to log in.',
      codeAccessibilityLabel: 'Six-digit registration verification code',
      codeResent: 'A new verification code was sent.',
      confirm: 'Confirm email',
      correctDetails: 'Correct registration details',
      description: 'Enter the six-digit code we sent to your email.',
      emailDestination: 'Code sent to {{email}}',
      expiredRegistration: 'This registration has expired. Return and create your account again.',
      genericError: "We couldn't verify your email. Please try again.",
      invalidCode: 'The verification code is invalid or expired.',
      invalidCodeFormat: 'Enter exactly six digits.',
      networkError: 'No internet connection. Check your connection and try again.',
      rateLimited: 'Too many attempts. Please wait before trying again.',
      resend: 'Resend code',
      resendIn: 'Resend code in {{time}}',
      serverUnavailable: 'The server is temporarily unavailable. Please try again later.',
      timeoutError: 'The request timed out. Please try again.',
      title: 'Verify your email',
    },
    otp: {
      codeAccessibilityLabel: 'Six-digit password recovery verification code',
      codeResent: 'If an account exists for this email, we sent a new verification code.',
      codeSentTo: 'Code sent to {{email}}',
      explanation: 'Enter the six-digit code from your email.',
      invalidCodeFormat: 'Enter exactly six digits.',
      resendCode: 'Resend code',
      resendIn: 'Resend in {{seconds}}s',
      title: 'Enter verification code',
    },
    recovery: {
      back: 'Back',
      backToLogin: 'Back to login',
      invalidOrExpiredCode: 'The verification code is invalid or expired.',
      networkError: 'No internet connection. Check your connection and try again.',
      rateLimited: 'Too many requests. Please wait before trying again.',
      serverUnavailable: 'The server is temporarily unavailable. Please try again later.',
      timeoutError: 'The request timed out. Please try again.',
      tooManyAttempts: 'Too many unsuccessful attempts. Request a new verification code.',
      usedCode: 'This verification code has already been used. Request a new code.',
    },
    resetPassword: {
      confirmNewPassword: 'Confirm new password',
      explanation: 'Choose a new password for your FastRep account.',
      newPassword: 'New password',
      resetPassword: 'Reset password',
      success: 'Your password was reset. Log in with your new password.',
      title: 'Reset password',
      validation: {
        confirmPasswordRequired: 'Confirm your new password.',
        passwordMax: 'Password must contain no more than 128 characters.',
        passwordMin: 'Password must contain at least 8 characters.',
        passwordRequired: 'Password is required.',
        passwordsMismatch: 'Passwords do not match.',
      },
    },
    session: {
      expired: 'Your session has expired. Please log in again.',
      genericError: "We couldn't complete authentication. Please try again.",
      networkUnavailable: 'No internet connection. Check your connection and try again.',
      restoring: 'Restoring your session…',
      serverError: 'The server is temporarily unavailable. Please try again later.',
      timeout: 'The request timed out. Please try again.',
    },
  },
  common: {
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    continue: 'Continue',
    error: 'Error',
    info: 'Info',
    loading: 'Loading',
    no: 'No',
    retry: 'Retry',
    save: 'Save',
    somethingWentWrong: 'Something went wrong',
    success: 'Success',
    yes: 'Yes',
  },
  profile: {
    logout: 'Log out',
    logoutError: "You were logged out on this device, but we couldn't notify the server.",
    title: 'Profile',
  },
  reports: {
    card: {
      created: 'Created {{date}}',
      updated: 'Updated {{date}}',
    },
    create: {
      action: 'Create report',
      success: 'Report created successfully.',
      title: 'Create report',
    },
    delete: {
      action: 'Delete',
      alreadyDeleted: 'Report was already deleted.',
      confirmation: 'This action cannot be undone. The report will be permanently deleted.',
      success: 'Report deleted successfully.',
      title: 'Delete report?',
    },
    details: {
      createdAt: 'Created',
      errorDescription: 'We could not load this report. Please try again.',
      errorTitle: 'Unable to load report',
      noNotes: 'No notes',
      notFoundDescription: 'This report may have been deleted or is no longer available.',
      notFoundTitle: 'Report not found',
      title: 'Report details',
      updatedAt: 'Updated',
    },
    edit: {
      action: 'Edit',
      success: 'Report updated successfully.',
      title: 'Edit report',
    },
    errors: {
      network: 'No internet connection. Check your connection and try again.',
      notFound: 'The report was not found.',
      server: 'The server is temporarily unavailable. Please try again later.',
      timeout: 'The request timed out. Please try again.',
      validation: 'Check the report details and try again.',
    },
    form: {
      notes: 'Notes',
      notesPlaceholder: 'Add any useful details',
      title: 'Title',
      titlePlaceholder: 'Report title',
    },
    list: {
      emptyDescription: 'Create your first report to keep its progress and notes in one place.',
      emptyTitle: 'No reports yet',
      errorDescription: 'We could not load your reports. Check your connection and try again.',
      errorTitle: 'Unable to load reports',
      title: 'Reports',
    },
    status: {
      draft: 'Draft',
      failed: 'Failed',
      processing: 'Processing',
      ready: 'Ready',
    },
    validation: {
      notesMax: 'Notes must contain no more than 50,000 characters.',
      titleMax: 'Title must contain no more than 120 characters.',
      titleRequired: 'Title is required.',
    },
  },
  languages: {
    english: 'English',
    french: 'French',
    german: 'German',
    spanish: 'Spanish',
    ukrainian: 'Ukrainian',
  },
  showcase: {
    currentLanguage: 'Current language',
    description: 'Reusable application foundation showcase',
    showError: 'Show error',
    showSuccess: 'Show success',
    title: 'FastRep Foundation',
  },
};
