import type { TranslationResources } from './types';

export const es: TranslationResources = {
  auth: {
    forgotPassword: {
      codeSent: 'Código de verificación enviado',
      email: 'Correo electrónico',
      explanation: 'Introduce tu correo para recibir un código de verificación de seis dígitos.',
      sendCode: 'Enviar código',
      title: 'Contraseña olvidada',
      validation: {
        emailInvalid: 'Introduce un correo electrónico válido.',
        emailRequired: 'El correo electrónico es obligatorio.',
      },
    },
    login: {
      createAccount: 'Crear cuenta',
      description: 'Inicia sesión para seguir usando FastRep.',
      email: 'Correo electrónico',
      forgotPassword: '¿Has olvidado tu contraseña?',
      invalidCredentials: 'El correo electrónico o la contraseña son incorrectos.',
      logIn: 'Iniciar sesión',
      password: 'Contraseña',
      title: 'Te damos la bienvenida de nuevo',
      validation: {
        emailInvalid: 'Introduce un correo electrónico válido.',
        emailRequired: 'El correo electrónico es obligatorio.',
        passwordMax: 'La contraseña no puede superar los 128 caracteres.',
        passwordMin: 'La contraseña debe tener al menos 8 caracteres.',
        passwordRequired: 'La contraseña es obligatoria.',
      },
    },
    registration: {
      alreadyHaveAccount: '¿Ya tienes una cuenta?',
      confirmPassword: 'Confirmar contraseña',
      createAccount: 'Crear cuenta',
      email: 'Correo electrónico',
      fullName: 'Nombre completo',
      logIn: 'Iniciar sesión',
      password: 'Contraseña',
      subtitle: 'Crea tu cuenta de FastRep para comenzar.',
      title: 'Crea tu cuenta',
      validation: {
        confirmPasswordRequired: 'Confirma tu contraseña.',
        emailInvalid: 'Introduce un correo electrónico válido.',
        emailRequired: 'El correo electrónico es obligatorio.',
        fullNameMax: 'El nombre completo no puede superar los 80 caracteres.',
        fullNameMin: 'El nombre completo debe tener al menos 2 caracteres.',
        fullNameRequired: 'El nombre completo es obligatorio.',
        passwordMax: 'La contraseña no puede superar los 128 caracteres.',
        passwordMin: 'La contraseña debe tener al menos 8 caracteres.',
        passwordRequired: 'La contraseña es obligatoria.',
        passwordsMismatch: 'Las contraseñas no coinciden.',
      },
    },
    registrationVerification: {
      accountAlreadyExists: 'Ya existe una cuenta con este correo. Vuelve para iniciar sesión.',
      codeAccessibilityLabel: 'Código de verificación de registro de seis dígitos',
      codeResent: 'Nuevo código de verificación enviado',
      confirm: 'Confirmar correo',
      correctDetails: 'Corregir los datos de registro',
      description: 'Introduce el código de seis dígitos que enviamos a tu correo.',
      emailDestination: 'Código enviado a {{email}}',
      expiredRegistration: 'Este registro ha caducado. Vuelve y crea tu cuenta de nuevo.',
      genericError: 'No hemos podido verificar tu correo. Inténtalo de nuevo.',
      invalidCode: 'El código de verificación no es válido o ha caducado.',
      invalidCodeFormat: 'Introduce exactamente seis dígitos.',
      networkError: 'No hay conexión a Internet. Comprueba tu conexión e inténtalo de nuevo.',
      rateLimited: 'Demasiados intentos. Espera antes de volver a intentarlo.',
      resend: 'Reenviar código',
      resendIn: 'Reenviar código en {{time}}',
      serverUnavailable: 'El servidor no está disponible temporalmente. Inténtalo más tarde.',
      timeoutError: 'La solicitud ha agotado el tiempo de espera. Inténtalo de nuevo.',
      title: 'Verifica tu correo',
    },
    otp: {
      codeResent: 'Nuevo código de verificación enviado',
      codeSentTo: 'Código enviado a {{email}}',
      explanation: 'Introduce el código de seis dígitos enviado a tu correo.',
      invalidCodeFormat: 'Introduce exactamente seis dígitos.',
      resendCode: 'Reenviar código',
      resendIn: 'Reenviar en {{seconds}} s',
      title: 'Introduce el código de verificación',
      verificationCode: 'Código de verificación',
    },
    recovery: {
      back: 'Atrás',
      backToLogin: 'Volver al inicio de sesión',
      invalidOrExpiredCode: 'El código de verificación no es válido o ha caducado.',
      networkError: 'No hay conexión a Internet. Comprueba la conexión e inténtalo de nuevo.',
      rateLimited: 'Demasiadas solicitudes. Espera antes de volver a intentarlo.',
      serverUnavailable: 'El servidor no está disponible temporalmente. Inténtalo más tarde.',
      timeoutError: 'La solicitud ha agotado el tiempo de espera.',
      tooManyAttempts: 'Demasiados intentos fallidos. Solicita un código nuevo.',
      usedCode: 'Este código ya se ha utilizado. Solicita un código nuevo.',
    },
    resetPassword: {
      confirmNewPassword: 'Confirmar contraseña nueva',
      explanation: 'Elige una contraseña nueva para tu cuenta de FastRep.',
      newPassword: 'Contraseña nueva',
      resetPassword: 'Restablecer contraseña',
      success: 'Contraseña cambiada',
      title: 'Restablecer contraseña',
      validation: {
        confirmPasswordRequired: 'Confirma tu contraseña nueva.',
        passwordMax: 'La contraseña no puede superar los 128 caracteres.',
        passwordMin: 'La contraseña debe tener al menos 8 caracteres.',
        passwordRequired: 'La contraseña es obligatoria.',
        passwordsMismatch: 'Las contraseñas no coinciden.',
      },
    },
    session: {
      expired: 'Tu sesión ha caducado. Vuelve a iniciar sesión.',
      genericError: 'No se pudo completar la autenticación. Inténtalo de nuevo.',
      networkUnavailable: 'No hay conexión a Internet. Comprueba la conexión e inténtalo de nuevo.',
      restoring: 'Restaurando tu sesión…',
      serverError: 'El servidor no está disponible temporalmente. Inténtalo de nuevo más tarde.',
      timeout: 'La solicitud ha agotado el tiempo de espera. Inténtalo de nuevo.',
    },
  },
  common: {
    back: 'Atrás',
    cancel: 'Cancelar',
    close: 'Cerrar',
    continue: 'Continuar',
    error: 'Error',
    info: 'Información',
    loading: 'Cargando',
    no: 'No',
    retry: 'Reintentar',
    save: 'Guardar',
    somethingWentWrong: 'Algo salió mal',
    success: 'Éxito',
    yes: 'Sí',
  },
  profile: {
    logout: 'Cerrar sesión',
    logoutError: 'Has cerrado sesión en este dispositivo, pero no se pudo notificar al servidor.',
    title: 'Perfil',
  },
  reports: {
    card: {
      created: 'Creado el {{date}}',
      updated: 'Actualizado el {{date}}',
    },
    create: {
      action: 'Crear informe',
      success: 'Informe creado',
      title: 'Crear informe',
    },
    delete: {
      action: 'Eliminar',
      alreadyDeleted: 'El informe ya se había eliminado.',
      confirmation: 'Esta acción no se puede deshacer. El informe se eliminará permanentemente.',
      success: 'Informe eliminado',
      title: '¿Eliminar informe?',
    },
    details: {
      createdAt: 'Creado',
      errorDescription: 'No se pudo cargar este informe. Inténtalo de nuevo.',
      errorTitle: 'No se pudo cargar el informe',
      noNotes: 'Sin notas',
      notFoundDescription: 'Es posible que este informe se haya eliminado o ya no esté disponible.',
      notFoundTitle: 'Informe no encontrado',
      title: 'Detalles del informe',
      updatedAt: 'Actualizado',
    },
    edit: {
      action: 'Editar',
      success: 'Informe actualizado',
      title: 'Editar informe',
    },
    errors: {
      network: 'No hay conexión a Internet. Comprueba la conexión e inténtalo de nuevo.',
      notFound: 'No se encontró el informe.',
      server: 'El servidor no está disponible temporalmente. Inténtalo más tarde.',
      timeout: 'La solicitud agotó el tiempo de espera. Inténtalo de nuevo.',
      validation: 'Comprueba los datos del informe e inténtalo de nuevo.',
    },
    form: {
      notes: 'Notas',
      notesPlaceholder: 'Añade información útil',
      title: 'Título',
      titlePlaceholder: 'Título del informe',
    },
    list: {
      emptyDescription: 'Crea tu primer informe para guardar su progreso y sus notas en un solo lugar.',
      emptyTitle: 'Aún no hay informes',
      errorDescription: 'No se pudieron cargar tus informes. Comprueba la conexión e inténtalo de nuevo.',
      errorTitle: 'No se pudieron cargar los informes',
      title: 'Informes',
    },
    status: {
      draft: 'Borrador',
      failed: 'Fallido',
      processing: 'Procesando',
      ready: 'Listo',
    },
    validation: {
      notesMax: 'Las notas no pueden superar los 50.000 caracteres.',
      titleMax: 'El título no puede superar los 120 caracteres.',
      titleRequired: 'El título es obligatorio.',
    },
  },
  languages: {
    english: 'Inglés',
    french: 'Francés',
    german: 'Alemán',
    spanish: 'Español',
    ukrainian: 'Ucraniano',
  },
  showcase: {
    currentLanguage: 'Idioma actual',
    description: 'Demostración de la base reutilizable de la aplicación',
    showError: 'Mostrar error',
    showSuccess: 'Mostrar éxito',
    successMessage: 'Los avisos de éxito de dos líneas admiten detalles adicionales.',
    successTitle: 'Cambios guardados',
    title: 'Base FastRep',
  },
};
