import type { TranslationResources } from './types';

export const es: TranslationResources = {
  auth: {
    environment: {
      productionRequired: 'Esta cuenta solo puede usar el entorno de Producción. Inicia sesión de nuevo.',
    },
    forgotPassword: {
      codeSent: 'Código de verificación enviado',
      email: 'Correo electrónico',
      explanation: 'Introduce tu correo para recibir un código de verificación de seis dígitos.',
      sendCode: 'Enviar código',
      title: 'Contraseña olvidada',
      validation: {
        emailInvalid: 'Introduce un correo electrónico válido.',
        emailRequired: 'El correo electrónico es obligatorio.',
      },
    },
    login: {
      createAccount: 'Crear cuenta',
      description: 'Inicia sesión para seguir usando FastRep.',
      email: 'Correo electrónico',
      forgotPassword: '¿Has olvidado tu contraseña?',
      invalidCredentials: 'El correo electrónico o la contraseña son incorrectos.',
      logIn: 'Iniciar sesión',
      password: 'Contraseña',
      title: 'Te damos la bienvenida de nuevo',
      validation: {
        emailInvalid: 'Introduce un correo electrónico válido.',
        emailRequired: 'El correo electrónico es obligatorio.',
        passwordMax: 'La contraseña no puede superar los 128 caracteres.',
        passwordMin: 'La contraseña debe tener al menos 8 caracteres.',
        passwordRequired: 'La contraseña es obligatoria.',
      },
    },
    registration: {
      alreadyHaveAccount: '¿Ya tienes una cuenta?',
      confirmPassword: 'Confirmar contraseña',
      createAccount: 'Crear cuenta',
      email: 'Correo electrónico',
      fullName: 'Nombre completo',
      logIn: 'Iniciar sesión',
      password: 'Contraseña',
      subtitle: 'Crea tu cuenta de FastRep para comenzar.',
      title: 'Crea tu cuenta',
      validation: {
        confirmPasswordRequired: 'Confirma tu contraseña.',
        emailInvalid: 'Introduce un correo electrónico válido.',
        emailRequired: 'El correo electrónico es obligatorio.',
        fullNameMax: 'El nombre completo no puede superar los 80 caracteres.',
        fullNameMin: 'El nombre completo debe tener al menos 2 caracteres.',
        fullNameRequired: 'El nombre completo es obligatorio.',
        passwordMax: 'La contraseña no puede superar los 128 caracteres.',
        passwordMin: 'La contraseña debe tener al menos 8 caracteres.',
        passwordRequired: 'La contraseña es obligatoria.',
        passwordsMismatch: 'Las contraseñas no coinciden.',
      },
    },
    registrationVerification: {
      accountAlreadyExists: 'Ya existe una cuenta con este correo. Vuelve para iniciar sesión.',
      codeAccessibilityLabel: 'Código de verificación de registro de seis dígitos',
      codeResent: 'Nuevo código de verificación enviado',
      confirm: 'Confirmar correo',
      correctDetails: 'Corregir los datos de registro',
      description: 'Introduce el código de seis dígitos que enviamos a tu correo.',
      emailDestination: 'Código enviado a {{email}}',
      expiredRegistration: 'Este registro ha caducado. Vuelve y crea tu cuenta de nuevo.',
      genericError: 'No hemos podido verificar tu correo. Inténtalo de nuevo.',
      invalidCode: 'El código de verificación no es válido o ha caducado.',
      invalidCodeFormat: 'Introduce exactamente seis dígitos.',
      networkError: 'No hay conexión a Internet. Comprueba tu conexión e inténtalo de nuevo.',
      rateLimited: 'Demasiados intentos. Espera antes de volver a intentarlo.',
      resend: 'Reenviar código',
      resendIn: 'Reenviar código en {{time}}',
      serverUnavailable: 'El servidor no está disponible temporalmente. Inténtalo más tarde.',
      timeoutError: 'La solicitud ha agotado el tiempo de espera. Inténtalo de nuevo.',
      title: 'Verifica tu correo',
    },
    otp: {
      codeAccessibilityLabel: 'Código de verificación de recuperación de contraseña de seis dígitos',
      codeResent: 'Nuevo código de verificación enviado',
      codeSentTo: 'Código enviado a {{email}}',
      explanation: 'Introduce el código de seis dígitos enviado a tu correo.',
      invalidCodeFormat: 'Introduce exactamente seis dígitos.',
      resendCode: 'Reenviar código',
      resendIn: 'Reenviar en {{seconds}} s',
      title: 'Introduce el código de verificación',
    },
    recovery: {
      back: 'Atrás',
      backToLogin: 'Volver al inicio de sesión',
      invalidOrExpiredCode: 'El código de verificación no es válido o ha caducado.',
      networkError: 'No hay conexión a Internet. Comprueba la conexión e inténtalo de nuevo.',
      rateLimited: 'Demasiadas solicitudes. Espera antes de volver a intentarlo.',
      serverUnavailable: 'El servidor no está disponible temporalmente. Inténtalo más tarde.',
      timeoutError: 'La solicitud ha agotado el tiempo de espera.',
      tooManyAttempts: 'Demasiados intentos fallidos. Solicita un código nuevo.',
      usedCode: 'Este código ya se ha utilizado. Solicita un código nuevo.',
    },
    resetPassword: {
      confirmNewPassword: 'Confirmar contraseña nueva',
      explanation: 'Elige una contraseña nueva para tu cuenta de FastRep.',
      newPassword: 'Contraseña nueva',
      resetPassword: 'Restablecer contraseña',
      success: 'Contraseña cambiada',
      title: 'Restablecer contraseña',
      validation: {
        confirmPasswordRequired: 'Confirma tu contraseña nueva.',
        passwordMax: 'La contraseña no puede superar los 128 caracteres.',
        passwordMin: 'La contraseña debe tener al menos 8 caracteres.',
        passwordRequired: 'La contraseña es obligatoria.',
        passwordsMismatch: 'Las contraseñas no coinciden.',
      },
    },
    session: {
      expired: 'Tu sesión ha caducado. Vuelve a iniciar sesión.',
      genericError: 'No se pudo completar la autenticación. Inténtalo de nuevo.',
      networkUnavailable: 'No hay conexión a Internet. Comprueba la conexión e inténtalo de nuevo.',
      restoring: 'Restaurando tu sesión…',
      serverError: 'El servidor no está disponible temporalmente. Inténtalo de nuevo más tarde.',
      timeout: 'La solicitud ha agotado el tiempo de espera. Inténtalo de nuevo.',
    },
  },
  common: {
    back: 'Atrás',
    cancel: 'Cancelar',
    close: 'Cerrar',
    continue: 'Continuar',
    error: 'Error',
    info: 'Información',
    loading: 'Cargando',
    no: 'No',
    retry: 'Reintentar',
    save: 'Guardar',
    somethingWentWrong: 'Algo salió mal',
    success: 'Éxito',
    yes: 'Sí',
  },
  profile: {
    environment: {
      confirmationMessage: 'Se cerrará tu sesión y te conectarás al entorno {{environment}}.',
      confirmationTitle: '¿Cambiar de entorno?',
      developmentIndicator: 'Entorno de Desarrollo',
      selectionMessage: 'Elige el entorno de API para tu próxima sesión.',
      switchAction: 'Cambiar',
      title: 'Entorno',
    },
    logout: 'Cerrar sesión',
    logoutError: 'Has cerrado sesión en este dispositivo, pero no se pudo notificar al servidor.',
    title: 'Perfil',
  },
  reports: {
    attachments: {
      audio: 'Audio', camera: 'Cámara', cameraPermission: 'Permite el acceso a la cámara para tomar una foto.', confirmFailed: 'No se pudo verificar el archivo adjunto', empty: 'Aún no hay archivos adjuntos', file: 'Archivo', invalid: 'Archivo adjunto no compatible', microphonePermission: 'Permite el acceso al micrófono para grabar audio.', permissionTitle: 'Permiso necesario', photo: 'Foto', photoFailed: 'No se pudo añadir la foto', recording: 'Grabando · {{duration}}', recordingFailed: 'No se pudo grabar el audio', remove: 'Eliminar', removeFailed: 'No se pudo eliminar el archivo adjunto',
      states: { CONFIRMING: 'Verificando', FAILED: 'Error de carga', LOCAL: 'En espera', READY: 'Listo', REQUESTING_UPLOAD: 'Preparando', UPLOADING: 'Cargando' }, stop: 'Detener', title: 'Archivos adjuntos', tryAgain: 'Inténtalo de nuevo.', types: { AUDIO: 'Audio', DOCUMENT: 'Archivo', IMAGE: 'Foto' }, uploadFailed: 'Error al cargar el archivo adjunto',
      validation: { audioDurationTooLong: 'Las grabaciones de audio pueden durar hasta 20 minutos.', fileTooLarge: 'Este archivo es demasiado grande.', imageDimensionsTooLarge: 'Las imágenes pueden tener hasta 4096 × 4096 píxeles.', missingFileMetadata: 'No se pudo leer el archivo seleccionado.', reportTotalTooLarge: 'Los archivos adjuntos de un informe pueden sumar hasta 150 MB.', tooManyFiles: 'Este informe alcanzó el límite para este tipo de archivo.', unsupportedType: 'Elige un formato de archivo compatible.' },
    },
    card: {
      created: 'Creado el {{date}}',
      updated: 'Actualizado el {{date}}',
    },
    create: {
      action: 'Crear informe',
      success: 'Informe creado',
      title: 'Crear informe',
    },
    delete: {
      action: 'Eliminar',
      alreadyDeleted: 'El informe ya se había eliminado.',
      confirmation: 'Esta acción no se puede deshacer. El informe se eliminará permanentemente.',
      success: 'Informe eliminado',
      title: '¿Eliminar informe?',
    },
    details: {
      createdAt: 'Creado',
      errorDescription: 'No se pudo cargar este informe. Inténtalo de nuevo.',
      errorTitle: 'No se pudo cargar el informe',
      noNotes: 'Sin notas',
      notFoundDescription: 'Es posible que este informe se haya eliminado o ya no esté disponible.',
      notFoundTitle: 'Informe no encontrado',
      title: 'Detalles del informe',
      updatedAt: 'Actualizado',
    },
    edit: {
      action: 'Editar',
      success: 'Informe actualizado',
      title: 'Editar informe',
    },
    errors: {
      network: 'No hay conexión a Internet. Comprueba la conexión e inténtalo de nuevo.',
      notFound: 'No se encontró el informe.',
      server: 'El servidor no está disponible temporalmente. Inténtalo más tarde.',
      timeout: 'La solicitud agotó el tiempo de espera. Inténtalo de nuevo.',
      validation: 'Comprueba los datos del informe e inténtalo de nuevo.',
    },
    form: {
      notes: 'Notas',
      notesPlaceholder: 'Añade información útil',
      title: 'Título',
      titlePlaceholder: 'Título del informe',
    },
    generation: {
      cancel: 'Cancelar generación', cancelFailed: 'No se pudo cancelar la generación', credits: '{{count}} créditos',
      errors: { GENERATION_ALREADY_ACTIVE: 'Ya hay una generación en curso para este informe.', GENERATION_CREDITS_EXHAUSTED: 'No tienes créditos de generación disponibles.', GENERATION_CREDIT_RESERVATION_FAILED: 'No se pudo reservar un crédito. Inténtalo de nuevo.', GENERATION_DAILY_LIMIT_REACHED: 'Se alcanzó el límite diario de generación.', GENERATION_DISABLED: 'La generación de informes no está disponible temporalmente.', GENERATION_QUEUE_UNAVAILABLE: 'El servicio de generación no está disponible temporalmente.', GENERATION_RATE_LIMITED: 'Demasiadas solicitudes. Espera un momento e inténtalo de nuevo.', REPORT_HAS_NO_CONTENT: 'Añade notas o al menos un archivo adjunto.', REPORT_HAS_PENDING_UPLOADS: 'Espera a que terminen de cargarse todos los archivos.', REPORT_HAS_REJECTED_ASSETS: 'Elimina los archivos adjuntos rechazados.', REPORT_NOT_EDITABLE: 'Este informe no se puede generar en su estado actual.', REPORT_TEMPORARILY_LOCKED: 'Este informe no está disponible temporalmente tras varios errores.', generic: 'No se pudo generar el informe. Inténtalo de nuevo.' },
      failedDescription: 'La generación falló. Edita las fuentes e inténtalo de nuevo.', generate: 'Generar informe', generated: 'Informe generado', lock: { message: 'Este informe falló varias veces. Inténtalo de nuevo en {{minutes}} minutos.', title: 'Informe no disponible temporalmente' }, regenerate: 'Regenerar', retry: 'Reintentar generación', stages: { analyzing: 'Analizando archivos adjuntos…', completed: 'Completado', creatingPdf: 'Creando PDF…', finalizing: 'Finalizando…', generating: 'Generando informe…', preparing: 'Preparando…', transcribing: 'Transcribiendo audio…' }, startFailed: 'Error de generación', title: 'Informe con IA',
    },
    list: {
      emptyDescription: 'Crea tu primer informe para guardar su progreso y sus notas en un solo lugar.',
      emptyTitle: 'Aún no hay informes',
      errorDescription: 'No se pudieron cargar tus informes. Comprueba la conexión e inténtalo de nuevo.',
      errorTitle: 'No se pudieron cargar los informes',
      title: 'Informes',
    },
    output: { open: 'Abrir informe', openFailed: 'No se pudo abrir el informe', share: 'Compartir informe', shareFailed: 'No se pudo compartir el informe', tryAgain: 'Descarga el PDF de nuevo y vuelve a intentarlo.' },
    status: {
      draft: 'Borrador',
      failed: 'Fallido',
      processing: 'Procesando',
      ready: 'Listo',
    },
    validation: {
      notesMax: 'Las notas no pueden superar los 50.000 caracteres.',
      titleMax: 'El título no puede superar los 120 caracteres.',
      titleRequired: 'El título es obligatorio.',
    },
  },
  languages: {
    english: 'Inglés',
    french: 'Francés',
    german: 'Alemán',
    spanish: 'Español',
    ukrainian: 'Ucraniano',
  },
  showcase: {
    currentLanguage: 'Idioma actual',
    description: 'Demostración de la base reutilizable de la aplicación',
    showError: 'Mostrar error',
    showSuccess: 'Mostrar éxito',
    successMessage: 'Los avisos de éxito de dos líneas admiten detalles adicionales.',
    successTitle: 'Cambios guardados',
    title: 'Base FastRep',
  },
};
