import type { TranslationResources } from './types';

export const fr: TranslationResources = {
  auth: {
    environment: {
      productionRequired: 'Ce compte peut uniquement utiliser l’environnement de Production. Reconnectez-vous.',
    },
    forgotPassword: {
      codeSent: 'Code de vérification envoyé',
      email: 'E-mail',
      explanation: 'Saisissez votre e-mail pour recevoir un code de vérification à six chiffres.',
      sendCode: 'Envoyer le code',
      title: 'Mot de passe oublié',
      validation: {
        emailInvalid: 'Saisissez une adresse e-mail valide.',
        emailRequired: "L'adresse e-mail est requise.",
      },
    },
    login: {
      createAccount: 'Créer un compte',
      description: 'Connectez-vous pour continuer à utiliser FastRep.',
      email: 'E-mail',
      forgotPassword: 'Mot de passe oublié ?',
      invalidCredentials: "L'adresse e-mail ou le mot de passe est incorrect.",
      logIn: 'Se connecter',
      password: 'Mot de passe',
      title: 'Bon retour',
      validation: {
        emailInvalid: 'Saisissez une adresse e-mail valide.',
        emailRequired: "L'adresse e-mail est requise.",
        passwordMax: 'Le mot de passe ne doit pas dépasser 128 caractères.',
        passwordMin: 'Le mot de passe doit contenir au moins 8 caractères.',
        passwordRequired: 'Le mot de passe est requis.',
      },
    },
    registration: {
      alreadyHaveAccount: 'Vous avez déjà un compte ?',
      confirmPassword: 'Confirmer le mot de passe',
      createAccount: 'Créer un compte',
      email: 'E-mail',
      fullName: 'Nom complet',
      logIn: 'Se connecter',
      password: 'Mot de passe',
      subtitle: 'Créez votre compte FastRep pour commencer.',
      title: 'Créer votre compte',
      validation: {
        confirmPasswordRequired: 'Confirmez votre mot de passe.',
        emailInvalid: 'Saisissez une adresse e-mail valide.',
        emailRequired: "L'adresse e-mail est requise.",
        fullNameMax: 'Le nom complet ne doit pas dépasser 80 caractères.',
        fullNameMin: 'Le nom complet doit contenir au moins 2 caractères.',
        fullNameRequired: 'Le nom complet est requis.',
        passwordMax: 'Le mot de passe ne doit pas dépasser 128 caractères.',
        passwordMin: 'Le mot de passe doit contenir au moins 8 caractères.',
        passwordRequired: 'Le mot de passe est requis.',
        passwordsMismatch: 'Les mots de passe ne correspondent pas.',
      },
    },
    registrationVerification: {
      accountAlreadyExists: 'Un compte existe déjà avec cet e-mail. Revenez à la connexion.',
      codeAccessibilityLabel: 'Code de vérification d’inscription à six chiffres',
      codeResent: 'Nouveau code de vérification envoyé',
      confirm: 'Confirmer l’e-mail',
      correctDetails: 'Corriger les informations d’inscription',
      description: 'Saisissez le code à six chiffres envoyé à votre adresse e-mail.',
      emailDestination: 'Code envoyé à {{email}}',
      expiredRegistration: 'Cette inscription a expiré. Revenez en arrière et recréez votre compte.',
      genericError: 'Impossible de vérifier votre e-mail. Veuillez réessayer.',
      invalidCode: 'Le code de vérification est incorrect ou a expiré.',
      invalidCodeFormat: 'Saisissez exactement six chiffres.',
      networkError: 'Aucune connexion Internet. Vérifiez votre connexion et réessayez.',
      rateLimited: 'Trop de tentatives. Veuillez patienter avant de réessayer.',
      resend: 'Renvoyer le code',
      resendIn: 'Renvoyer le code dans {{time}}',
      serverUnavailable: 'Le serveur est temporairement indisponible. Veuillez réessayer plus tard.',
      timeoutError: 'La requête a expiré. Veuillez réessayer.',
      title: 'Vérifiez votre e-mail',
    },
    otp: {
      codeAccessibilityLabel: 'Code de vérification de récupération du mot de passe à six chiffres',
      codeResent: 'Nouveau code de vérification envoyé',
      codeSentTo: 'Code envoyé à {{email}}',
      explanation: 'Saisissez le code à six chiffres reçu par e-mail.',
      invalidCodeFormat: 'Saisissez exactement six chiffres.',
      resendCode: 'Renvoyer le code',
      resendIn: 'Renvoyer dans {{seconds}} s',
      title: 'Saisir le code de vérification',
    },
    recovery: {
      back: 'Retour',
      backToLogin: 'Retour à la connexion',
      invalidOrExpiredCode: 'Le code de vérification est invalide ou expiré.',
      networkError: 'Aucune connexion Internet. Vérifiez votre connexion et réessayez.',
      rateLimited: 'Trop de demandes. Veuillez patienter avant de réessayer.',
      serverUnavailable: 'Le serveur est temporairement indisponible. Veuillez réessayer plus tard.',
      timeoutError: "Le délai d'attente de la requête a été dépassé.",
      tooManyAttempts: 'Trop de tentatives infructueuses. Demandez un nouveau code.',
      usedCode: 'Ce code a déjà été utilisé. Demandez un nouveau code.',
    },
    resetPassword: {
      confirmNewPassword: 'Confirmer le nouveau mot de passe',
      explanation: 'Choisissez un nouveau mot de passe pour votre compte FastRep.',
      newPassword: 'Nouveau mot de passe',
      resetPassword: 'Réinitialiser le mot de passe',
      success: 'Mot de passe modifié',
      title: 'Réinitialiser le mot de passe',
      validation: {
        confirmPasswordRequired: 'Confirmez votre nouveau mot de passe.',
        passwordMax: 'Le mot de passe ne doit pas dépasser 128 caractères.',
        passwordMin: 'Le mot de passe doit contenir au moins 8 caractères.',
        passwordRequired: 'Le mot de passe est requis.',
        passwordsMismatch: 'Les mots de passe ne correspondent pas.',
      },
    },
    session: {
      expired: 'Votre session a expiré. Veuillez vous reconnecter.',
      genericError: "L'authentification n'a pas pu aboutir. Veuillez réessayer.",
      networkUnavailable: 'Aucune connexion Internet. Vérifiez votre connexion et réessayez.',
      restoring: 'Restauration de votre session…',
      serverError: 'Le serveur est temporairement indisponible. Veuillez réessayer plus tard.',
      timeout: "Le délai d'attente de la requête a été dépassé. Veuillez réessayer.",
    },
  },
  common: {
    back: 'Retour',
    cancel: 'Annuler',
    close: 'Fermer',
    continue: 'Continuer',
    error: 'Erreur',
    info: 'Information',
    loading: 'Chargement',
    no: 'Non',
    retry: 'Réessayer',
    save: 'Enregistrer',
    somethingWentWrong: "Une erreur s'est produite",
    success: 'Succès',
    yes: 'Oui',
  },
  profile: {
    environment: {
      confirmationMessage: 'Vous serez déconnecté et relié à l’environnement {{environment}}.',
      confirmationTitle: 'Changer d’environnement ?',
      developmentIndicator: 'Environnement de Développement',
      selectionMessage: 'Choisissez l’environnement API de votre prochaine session.',
      switchAction: 'Changer',
      title: 'Environnement',
    },
    logout: 'Se déconnecter',
    logoutError: "Vous avez été déconnecté sur cet appareil, mais le serveur n'a pas pu être averti.",
    title: 'Profil',
  },
  reports: {
    attachments: {
      accessFailed: 'Impossible d’ouvrir la pièce jointe',
      attentionRequired: 'Une pièce jointe requiert votre attention',
      audioRecordingName: 'Enregistrement audio',
      delete: 'Supprimer',
      deleteAccessibility: 'Supprimer {{name}}',
      deleteConfirmation: 'Ce fichier ne sera plus inclus dans les prochaines générations du rapport.',
      deleteTitle: 'Supprimer la pièce jointe ?',
      fileName: 'Fichier',
      pauseAccessibility: 'Mettre {{name}} en pause',
      photoName: 'Photo',
      playFailed: 'Impossible de lire l’audio',
      playAccessibility: 'Lire {{name}}',
      rejectionReasons: {
        expired: 'Le téléversement a expiré. Ajoutez à nouveau la pièce jointe.',
        invalidContent: 'Le contenu du fichier n’a pas pu être traité.',
        limitExceeded: 'La limite de pièces jointes a été dépassée.',
        processingFailed: 'Cette pièce jointe n’a pas pu être traitée.',
        storageUnavailable: 'Le stockage était temporairement indisponible.',
        tooLarge: 'Cette pièce jointe est trop volumineuse.',
        unsupportedType: 'Ce type de fichier n’est pas pris en charge.',
      },
      removed: 'Pièce jointe supprimée',
      retryAccessibility: 'Réessayer {{name}}',
      audio: 'Audio',
      camera: 'Appareil photo',
      cameraPermission: 'Autorisez l’accès à l’appareil photo pour prendre une photo.',
      confirmFailed: 'Impossible de vérifier la pièce jointe',
      documentFailed: 'Impossible d’ajouter le fichier',
      empty: 'Aucune pièce jointe',
      file: 'Fichier',
      invalid: 'Pièce jointe non prise en charge',
      microphonePermission: 'Autorisez l’accès au microphone pour enregistrer un audio.',
      permissionTitle: 'Autorisation requise',
      photo: 'Photo',
      photoConversionFailed: 'Impossible de convertir cette photo dans un format pris en charge',
      photoFailed: 'Impossible d’ajouter la photo',
      recording: 'Enregistrement · {{duration}}',
      recordingFailed: 'Impossible d’enregistrer l’audio',
      remove: 'Supprimer',
      removeFailed: 'Impossible de supprimer la pièce jointe',
      states: {
        CONFIRMING: 'Vérification',
        FAILED: 'Échec du transfert',
        LOCAL: 'En attente',
        READY: 'Prêt',
        REQUESTING_UPLOAD: 'Préparation',
        UPLOADING: 'Transfert',
      },
      stop: 'Arrêter',
      title: 'Pièces jointes',
      tryAgain: 'Réessayez.',
      types: { AUDIO: 'Audio', DOCUMENT: 'Fichier', IMAGE: 'Photo' },
      uploadFailed: 'Échec du transfert de la pièce jointe',
      viewerUnavailable: 'Aucune application sur cet appareil ne peut ouvrir ce type de fichier',
      validation: {
        audioDurationTooLong: 'Les enregistrements audio sont limités à 20 minutes.',
        fileTooLarge: 'Ce fichier est trop volumineux.',
        imageDimensionsTooLarge: 'Les images sont limitées à 4096 × 4096 pixels.',
        missingFileMetadata: 'Le fichier sélectionné est illisible.',
        reportTotalTooLarge: 'Les pièces jointes d’un rapport sont limitées à 150 Mo.',
        tooManyFiles: 'La limite pour ce type de pièce jointe est atteinte.',
        unsupportedType: 'Choisissez un format de fichier pris en charge.',
      },
    },
    fallbackTitle: 'Nouveau rapport',
    card: {
      created: 'Créé le {{date}}',
      updated: 'Mis à jour le {{date}}',
    },
    create: {
      action: 'Créer un rapport',
      success: 'Rapport créé',
      title: 'Créer un rapport',
    },
    delete: {
      action: 'Supprimer',
      alreadyDeleted: 'Le rapport a déjà été supprimé.',
      confirmation: 'Cette action est irréversible. Le rapport sera définitivement supprimé.',
      success: 'Rapport supprimé',
      title: 'Supprimer le rapport ?',
    },
    details: {
      createdAt: 'Créé',
      errorDescription: 'Impossible de charger ce rapport. Veuillez réessayer.',
      errorTitle: 'Impossible de charger le rapport',
      noNotes: 'Aucune note',
      notFoundDescription: 'Ce rapport a peut-être été supprimé ou n’est plus disponible.',
      notFoundTitle: 'Rapport introuvable',
      title: 'Détails du rapport',
      updatedAt: 'Mis à jour',
    },
    duplicate: {
      action: 'Dupliquer',
      failed: 'Impossible de dupliquer le rapport',
    },
    edit: {
      action: 'Modifier',
      notEditableDescription: 'Seuls les brouillons et les rapports en échec peuvent être modifiés.',
      notEditableTitle: 'Ce rapport est final',
      success: 'Rapport mis à jour',
      title: 'Modifier le rapport',
    },
    errors: {
      network: 'Aucune connexion Internet. Vérifiez votre connexion et réessayez.',
      notFound: 'Le rapport est introuvable.',
      server: 'Le serveur est temporairement indisponible. Veuillez réessayer plus tard.',
      timeout: 'La demande a expiré. Veuillez réessayer.',
      validation: 'Vérifiez les informations du rapport et réessayez.',
    },
    form: {
      notes: 'Notes',
      notesPlaceholder: 'Ajoutez des informations utiles',
      title: 'Titre',
      titlePlaceholder: 'Titre du rapport',
    },
    generation: {
      rejectedAttachments: 'Réessayez ou supprimez la pièce jointe indiquée avant de générer le rapport.',
      cancel: 'Annuler la génération',
      cancelFailed: 'Impossible d’annuler la génération',
      credits: '{{count}} crédits',
      description: 'Transformez vos notes et pièces jointes en un rapport PDF soigné.',
      errors: {
        GENERATION_ALREADY_ACTIVE: 'Une génération est déjà en cours pour ce rapport.',
        GENERATION_CREDITS_EXHAUSTED: 'Aucun crédit de génération disponible.',
        GENERATION_CREDIT_RESERVATION_FAILED: 'Impossible de réserver un crédit. Réessayez.',
        GENERATION_DAILY_LIMIT_REACHED: 'La limite quotidienne de génération est atteinte.',
        GENERATION_DISABLED: 'La génération de rapports est temporairement indisponible.',
        GENERATION_QUEUE_UNAVAILABLE: 'Le service de génération est temporairement indisponible.',
        GENERATION_RATE_LIMITED: 'Trop de demandes. Patientez puis réessayez.',
        REPORT_HAS_NO_CONTENT: 'Ajoutez d’abord des notes ou une pièce jointe.',
        REPORT_HAS_PENDING_UPLOADS: 'Attendez la fin du transfert de toutes les pièces jointes.',
        REPORT_HAS_REJECTED_ASSETS: 'Supprimez les pièces jointes rejetées.',
        REPORT_NOT_EDITABLE: 'Ce rapport ne peut pas être généré dans son état actuel.',
        REPORT_TEMPORARILY_LOCKED: 'Ce rapport est temporairement indisponible après plusieurs échecs.',
        generic: 'Le rapport n’a pas pu être généré. Réessayez.',
      },
      failedDescription: 'La génération a échoué. Modifiez les sources et réessayez.',
      generate: 'Générer le rapport',
      generated: 'Rapport généré',
      lock: {
        message: 'Ce rapport a échoué plusieurs fois. Réessayez dans {{minutes}} minutes.',
        title: 'Rapport temporairement indisponible',
      },
      outputReady: 'Votre rapport est prêt',
      retry: 'Réessayer',
      stages: {
        analyzing: 'Analyse des pièces jointes…',
        completed: 'Terminé',
        creatingPdf: 'Création du PDF…',
        finalizing: 'Finalisation…',
        generating: 'Génération du rapport…',
        preparing: 'Préparation…',
        transcribing: 'Transcription audio…',
      },
      startFailed: 'Échec de la génération',
      title: 'Rapport IA',
    },
    list: {
      emptyDescription: 'Créez votre premier rapport pour suivre sa progression et ses notes au même endroit.',
      emptyTitle: 'Aucun rapport',
      errorDescription: 'Impossible de charger vos rapports. Vérifiez votre connexion et réessayez.',
      errorTitle: 'Impossible de charger les rapports',
      title: 'Rapports',
    },
    output: {
      open: 'Ouvrir le rapport',
      openFailed: 'Impossible d’ouvrir le rapport',
      share: 'Partager le rapport',
      shareFailed: 'Impossible de partager le rapport',
      tryAgain: 'Téléchargez à nouveau le PDF puis réessayez.',
      viewerUnavailable: 'Aucune application sur cet appareil ne peut ouvrir les fichiers PDF',
    },
    status: {
      draft: 'Brouillon',
      failed: 'Échec',
      processing: 'En traitement',
      queued: 'En attente',
      ready: 'Prêt',
    },
    validation: {
      notesMax: 'Les notes ne doivent pas dépasser 50 000 caractères.',
      titleMax: 'Le titre ne doit pas dépasser 120 caractères.',
      titleRequired: 'Le titre est obligatoire.',
    },
  },
  languages: {
    english: 'Anglais',
    french: 'Français',
    german: 'Allemand',
    spanish: 'Espagnol',
    ukrainian: 'Ukrainien',
  },
  showcase: {
    currentLanguage: 'Langue actuelle',
    description: "Présentation de la base réutilisable de l'application",
    showError: "Afficher l'erreur",
    showSuccess: 'Afficher le succès',
    successMessage: 'Les notifications de succès sur deux lignes acceptent des détails supplémentaires.',
    successTitle: 'Modifications enregistrées',
    title: 'Base FastRep',
  },
};
