import type { TranslationResources } from './types';

export const uk: TranslationResources = {
  auth: {
    environment: {
      productionRequired: 'Цей обліковий запис може використовувати лише Production. Увійдіть ще раз.',
    },
    forgotPassword: {
      codeSent: 'Код підтвердження надіслано',
      email: 'Електронна пошта',
      explanation: 'Введіть електронну пошту, щоб отримати шестизначний код підтвердження.',
      sendCode: 'Надіслати код',
      title: 'Забули пароль',
      validation: {
        emailInvalid: 'Введіть коректну адресу електронної пошти.',
        emailRequired: 'Електронна пошта обов’язкова.',
      },
    },
    login: {
      createAccount: 'Створити обліковий запис',
      description: 'Увійдіть, щоб продовжити користуватися FastRep.',
      email: 'Електронна пошта',
      forgotPassword: 'Забули пароль?',
      invalidCredentials: 'Електронну пошту або пароль введено неправильно.',
      logIn: 'Увійти',
      password: 'Пароль',
      title: 'З поверненням',
      validation: {
        emailInvalid: 'Введіть коректну адресу електронної пошти.',
        emailRequired: 'Електронна пошта обов’язкова.',
        passwordMax: 'Пароль не може містити більше ніж 128 символів.',
        passwordMin: 'Пароль має містити щонайменше 8 символів.',
        passwordRequired: 'Пароль обов’язковий.',
      },
    },
    registration: {
      alreadyHaveAccount: 'Уже маєте обліковий запис?',
      confirmPassword: 'Підтвердьте пароль',
      createAccount: 'Створити обліковий запис',
      email: 'Електронна пошта',
      fullName: "Повне ім'я",
      logIn: 'Увійти',
      password: 'Пароль',
      subtitle: 'Створіть обліковий запис FastRep, щоб почати.',
      title: 'Створіть обліковий запис',
      validation: {
        confirmPasswordRequired: 'Підтвердьте пароль.',
        emailInvalid: 'Введіть коректну адресу електронної пошти.',
        emailRequired: 'Електронна пошта обов’язкова.',
        fullNameMax: "Повне ім'я не може перевищувати 80 символів.",
        fullNameMin: "Повне ім'я має містити щонайменше 2 символи.",
        fullNameRequired: "Повне ім'я обов’язкове.",
        passwordMax: 'Пароль не може містити більше ніж 128 символів.',
        passwordMin: 'Пароль має містити щонайменше 8 символів.',
        passwordRequired: 'Пароль обов’язковий.',
        passwordsMismatch: 'Паролі не збігаються.',
      },
    },
    registrationVerification: {
      accountAlreadyExists: 'Обліковий запис із цією поштою вже існує. Поверніться до входу.',
      codeAccessibilityLabel: 'Шестизначний код підтвердження реєстрації',
      codeResent: 'Новий код підтвердження надіслано',
      confirm: 'Підтвердити пошту',
      correctDetails: 'Виправити дані реєстрації',
      description: 'Введіть шестизначний код, який ми надіслали на вашу пошту.',
      emailDestination: 'Код надіслано на {{email}}',
      expiredRegistration: 'Термін реєстрації минув. Поверніться та створіть обліковий запис знову.',
      genericError: 'Не вдалося підтвердити пошту. Повторіть спробу.',
      invalidCode: 'Код підтвердження неправильний або прострочений.',
      invalidCodeFormat: 'Введіть рівно шість цифр.',
      networkError: 'Немає з’єднання з інтернетом. Перевірте з’єднання та повторіть спробу.',
      rateLimited: 'Забагато спроб. Зачекайте перед повторною спробою.',
      resend: 'Надіслати код повторно',
      resendIn: 'Надіслати код повторно через {{time}}',
      serverUnavailable: 'Сервер тимчасово недоступний. Спробуйте пізніше.',
      timeoutError: 'Час очікування запиту минув. Повторіть спробу.',
      title: 'Підтвердьте пошту',
    },
    otp: {
      codeAccessibilityLabel: 'Шестизначний код підтвердження для відновлення пароля',
      codeResent: 'Новий код підтвердження надіслано',
      codeSentTo: 'Код надіслано на {{email}}',
      explanation: 'Введіть шестизначний код із листа.',
      invalidCodeFormat: 'Введіть рівно шість цифр.',
      resendCode: 'Надіслати код повторно',
      resendIn: 'Повторне надсилання через {{seconds}} с',
      title: 'Введіть код підтвердження',
    },
    recovery: {
      back: 'Назад',
      backToLogin: 'Повернутися до входу',
      invalidOrExpiredCode: 'Код підтвердження неправильний або прострочений.',
      networkError: 'Немає з’єднання з інтернетом. Перевірте з’єднання та повторіть спробу.',
      rateLimited: 'Забагато запитів. Зачекайте перед повторною спробою.',
      serverUnavailable: 'Сервер тимчасово недоступний. Спробуйте пізніше.',
      timeoutError: 'Час очікування запиту минув. Повторіть спробу.',
      tooManyAttempts: 'Забагато невдалих спроб. Запросіть новий код.',
      usedCode: 'Цей код уже використано. Запросіть новий код.',
    },
    resetPassword: {
      confirmNewPassword: 'Підтвердьте новий пароль',
      explanation: 'Оберіть новий пароль для облікового запису FastRep.',
      newPassword: 'Новий пароль',
      resetPassword: 'Скинути пароль',
      success: 'Пароль змінено',
      title: 'Скинути пароль',
      validation: {
        confirmPasswordRequired: 'Підтвердьте новий пароль.',
        passwordMax: 'Пароль не може містити більше ніж 128 символів.',
        passwordMin: 'Пароль має містити щонайменше 8 символів.',
        passwordRequired: 'Пароль обов’язковий.',
        passwordsMismatch: 'Паролі не збігаються.',
      },
    },
    session: {
      expired: 'Термін дії сеансу минув. Увійдіть знову.',
      genericError: 'Не вдалося завершити автентифікацію. Повторіть спробу.',
      networkUnavailable: 'Немає з’єднання з інтернетом. Перевірте з’єднання та повторіть спробу.',
      restoring: 'Відновлюємо сеанс…',
      serverError: 'Сервер тимчасово недоступний. Спробуйте пізніше.',
      timeout: 'Час очікування запиту минув. Повторіть спробу.',
    },
  },
  common: {
    back: 'Назад',
    cancel: 'Скасувати',
    close: 'Закрити',
    continue: 'Продовжити',
    error: 'Помилка',
    info: 'Інформація',
    loading: 'Завантаження',
    no: 'Ні',
    retry: 'Повторити',
    save: 'Зберегти',
    somethingWentWrong: 'Щось пішло не так',
    success: 'Успішно',
    yes: 'Так',
  },
  profile: {
    environment: {
      confirmationMessage: 'Ви вийдете з облікового запису та підключитеся до середовища {{environment}}.',
      confirmationTitle: 'Змінити середовище?',
      developmentIndicator: 'Середовище Development',
      selectionMessage: 'Виберіть API-середовище для наступного сеансу.',
      switchAction: 'Змінити',
      title: 'Середовище',
    },
    logout: 'Вийти',
    logoutError: 'Ви вийшли з облікового запису на цьому пристрої, але повідомити сервер не вдалося.',
    title: 'Профіль',
  },
  reports: {
    attachments: {
      accessFailed: 'Не вдалося відкрити вкладення',
      attentionRequired: 'Вкладення потребує уваги',
      audioRecordingName: 'Аудіозапис',
      delete: 'Видалити',
      deleteAccessibility: 'Видалити {{name}}',
      deleteConfirmation: 'Цей файл більше не буде враховано під час майбутніх генерацій звіту.',
      deleteTitle: 'Видалити вкладення?',
      fileName: 'Файл',
      pauseAccessibility: 'Призупинити {{name}}',
      photoName: 'Фото',
      playFailed: 'Не вдалося відтворити аудіо',
      playAccessibility: 'Відтворити {{name}}',
      rejectionReasons: {
        expired: 'Термін завантаження минув. Додайте вкладення знову.',
        invalidContent: 'Не вдалося обробити вміст файлу.',
        limitExceeded: 'Перевищено ліміт вкладень.',
        processingFailed: 'Не вдалося обробити це вкладення.',
        storageUnavailable: 'Сховище тимчасово недоступне.',
        tooLarge: 'Це вкладення завелике.',
        unsupportedType: 'Цей тип файлу не підтримується.',
      },
      removed: 'Вкладення видалено',
      retryAccessibility: 'Повторити для {{name}}',
      audio: 'Аудіо', camera: 'Камера', cameraPermission: 'Дозвольте доступ до камери, щоб зробити фото.', confirmFailed: 'Не вдалося перевірити вкладення', documentFailed: 'Не вдалося додати файл',
      empty: 'Вкладень ще немає', file: 'Файл', invalid: 'Вкладення не підтримується', microphonePermission: 'Дозвольте доступ до мікрофона для запису аудіо.',
      permissionTitle: 'Потрібен дозвіл', photo: 'Фото', photoConversionFailed: 'Не вдалося перетворити це фото на підтримуваний формат', photoFailed: 'Не вдалося додати фото', recording: 'Запис · {{duration}}', recordingFailed: 'Не вдалося записати аудіо',
      remove: 'Видалити', removeFailed: 'Не вдалося видалити вкладення',
      states: { CONFIRMING: 'Перевірка', FAILED: 'Помилка завантаження', LOCAL: 'Очікування', READY: 'Готово', REQUESTING_UPLOAD: 'Підготовка', UPLOADING: 'Завантаження' },
      stop: 'Зупинити', title: 'Вкладення', tryAgain: 'Спробуйте ще раз.', types: { AUDIO: 'Аудіо', DOCUMENT: 'Файл', IMAGE: 'Фото' }, uploadFailed: 'Не вдалося завантажити вкладення',
      validation: { audioDurationTooLong: 'Аудіозапис може тривати до 20 хвилин.', fileTooLarge: 'Цей файл завеликий.', imageDimensionsTooLarge: 'Зображення може бути до 4096 × 4096 пікселів.', missingFileMetadata: 'Не вдалося прочитати вибраний файл.', reportTotalTooLarge: 'Загальний розмір вкладень звіту — до 150 МБ.', tooManyFiles: 'Досягнуто ліміту вкладень цього типу.', unsupportedType: 'Виберіть підтримуваний формат файлу.' },
    },
    fallbackTitle: 'Новий звіт',
    card: {
      created: 'Створено {{date}}',
      updated: 'Оновлено {{date}}',
    },
    create: {
      action: 'Створити звіт',
      success: 'Звіт створено',
      title: 'Створити звіт',
    },
    delete: {
      action: 'Видалити',
      alreadyDeleted: 'Звіт уже було видалено.',
      confirmation: 'Цю дію неможливо скасувати. Звіт буде видалено назавжди.',
      success: 'Звіт видалено',
      title: 'Видалити звіт?',
    },
    details: {
      createdAt: 'Створено',
      errorDescription: 'Не вдалося завантажити цей звіт. Спробуйте ще раз.',
      errorTitle: 'Не вдалося завантажити звіт',
      noNotes: 'Нотаток немає',
      notFoundDescription: 'Можливо, цей звіт видалено або він більше недоступний.',
      notFoundTitle: 'Звіт не знайдено',
      title: 'Деталі звіту',
      updatedAt: 'Оновлено',
    },
    edit: {
      action: 'Редагувати',
      success: 'Звіт оновлено',
      title: 'Редагувати звіт',
    },
    errors: {
      network: 'Немає з’єднання з інтернетом. Перевірте мережу й спробуйте ще раз.',
      notFound: 'Звіт не знайдено.',
      server: 'Сервер тимчасово недоступний. Спробуйте пізніше.',
      timeout: 'Час очікування запиту вичерпано. Спробуйте ще раз.',
      validation: 'Перевірте дані звіту й спробуйте ще раз.',
    },
    form: {
      notes: 'Нотатки',
      notesPlaceholder: 'Додайте корисні деталі',
      title: 'Назва',
      titlePlaceholder: 'Назва звіту',
    },
    generation: {
      cancel: 'Скасувати генерацію', cancelFailed: 'Не вдалося скасувати генерацію', credits: 'Кредитів: {{count}}', description: 'Перетворіть нотатки та вкладення на готовий PDF-звіт.',
      rejectedAttachments: 'Повторіть або видаліть позначене вкладення перед генерацією звіту.',
      errors: { GENERATION_ALREADY_ACTIVE: 'Генерація цього звіту вже виконується.', GENERATION_CREDITS_EXHAUSTED: 'Немає доступних кредитів генерації.', GENERATION_CREDIT_RESERVATION_FAILED: 'Не вдалося зарезервувати кредит. Спробуйте ще раз.', GENERATION_DAILY_LIMIT_REACHED: 'Досягнуто денного ліміту генерацій.', GENERATION_DISABLED: 'Генерація звітів тимчасово недоступна.', GENERATION_QUEUE_UNAVAILABLE: 'Сервіс генерації тимчасово недоступний.', GENERATION_RATE_LIMITED: 'Забагато запитів. Зачекайте та повторіть.', REPORT_HAS_NO_CONTENT: 'Спочатку додайте нотатки або вкладення.', REPORT_HAS_PENDING_UPLOADS: 'Дочекайтеся завершення завантаження вкладень.', REPORT_HAS_REJECTED_ASSETS: 'Видаліть відхилені вкладення.', REPORT_NOT_EDITABLE: 'Звіт не можна згенерувати в поточному стані.', REPORT_TEMPORARILY_LOCKED: 'Звіт тимчасово недоступний після повторних помилок.', generic: 'Не вдалося згенерувати звіт. Спробуйте ще раз.' },
      failedDescription: 'Генерація не вдалася. Відредагуйте джерела та повторіть.', generate: 'Згенерувати звіт', generated: 'Звіт згенеровано',
      lock: { message: 'Цей звіт кілька разів не вдалося створити. Повторіть через {{minutes}} хв.', title: 'Звіт тимчасово недоступний' }, outputReady: 'Ваш звіт готовий', regenerate: 'Згенерувати знову', retry: 'Повторити генерацію',
      stages: { analyzing: 'Аналіз вкладень…', completed: 'Завершено', creatingPdf: 'Створення PDF…', finalizing: 'Завершення…', generating: 'Генерація звіту…', preparing: 'Підготовка…', transcribing: 'Розшифровка аудіо…' }, startFailed: 'Помилка генерації', title: 'AI-звіт',
    },
    list: {
      emptyDescription: 'Створіть перший звіт, щоб зберігати його прогрес і нотатки в одному місці.',
      emptyTitle: 'Звітів ще немає',
      errorDescription: 'Не вдалося завантажити звіти. Перевірте з’єднання й спробуйте ще раз.',
      errorTitle: 'Не вдалося завантажити звіти',
      title: 'Звіти',
    },
    output: { open: 'Відкрити звіт', openFailed: 'Не вдалося відкрити звіт', share: 'Поділитися звітом', shareFailed: 'Не вдалося поділитися звітом', tryAgain: 'Завантажте PDF ще раз і повторіть.' },
    status: {
      draft: 'Чернетка',
      failed: 'Помилка',
      processing: 'Обробляється',
      ready: 'Готовий',
    },
    validation: {
      notesMax: 'Нотатки мають містити не більше 50 000 символів.',
      titleMax: 'Назва має містити не більше 120 символів.',
      titleRequired: 'Назва обов’язкова.',
    },
  },
  languages: {
    english: 'Англійська',
    french: 'Французька',
    german: 'Німецька',
    spanish: 'Іспанська',
    ukrainian: 'Українська',
  },
  showcase: {
    currentLanguage: 'Поточна мова',
    description: 'Демонстрація багаторазової основи застосунку',
    showError: 'Показати помилку',
    showSuccess: 'Показати успіх',
    successMessage: 'Дворядкові повідомлення про успіх підтримують додаткові деталі.',
    successTitle: 'Зміни збережено',
    title: 'Основа FastRep',
  },
};
