import type { TranslationResources } from './types';

export const uk: TranslationResources = {
  auth: {
    login: {
      createAccount: 'Створити обліковий запис',
      description: 'Увійдіть, щоб продовжити користуватися FastRep.',
      email: 'Електронна пошта',
      forgotPassword: 'Забули пароль?',
      invalidCredentials: 'Електронну пошту або пароль введено неправильно.',
      logIn: 'Увійти',
      password: 'Пароль',
      passwordRecoveryComingSoon: 'Відновлення пароля незабаром стане доступним.',
      title: 'З поверненням',
      validation: {
        emailInvalid: 'Введіть коректну адресу електронної пошти.',
        emailRequired: 'Електронна пошта обов’язкова.',
        passwordMax: 'Пароль не може містити більше ніж 128 символів.',
        passwordMin: 'Пароль має містити щонайменше 8 символів.',
        passwordRequired: 'Пароль обов’язковий.',
      },
    },
    registration: {
      alreadyHaveAccount: 'Уже маєте обліковий запис?',
      confirmPassword: 'Підтвердьте пароль',
      createAccount: 'Створити обліковий запис',
      email: 'Електронна пошта',
      fullName: "Повне ім'я",
      logIn: 'Увійти',
      password: 'Пароль',
      subtitle: 'Створіть обліковий запис FastRep, щоб почати.',
      title: 'Створіть обліковий запис',
      validation: {
        confirmPasswordRequired: 'Підтвердьте пароль.',
        emailInvalid: 'Введіть коректну адресу електронної пошти.',
        emailRequired: 'Електронна пошта обов’язкова.',
        fullNameMax: "Повне ім'я не може перевищувати 80 символів.",
        fullNameMin: "Повне ім'я має містити щонайменше 2 символи.",
        fullNameRequired: "Повне ім'я обов’язкове.",
        passwordMin: 'Пароль має містити щонайменше 8 символів.',
        passwordRequired: 'Пароль обов’язковий.',
        passwordsMismatch: 'Паролі не збігаються.',
      },
    },
    session: {
      expired: 'Термін дії сеансу минув. Увійдіть знову.',
      genericError: 'Не вдалося завершити автентифікацію. Повторіть спробу.',
      networkUnavailable:
        'Немає з’єднання з інтернетом. Перевірте з’єднання та повторіть спробу.',
      restoring: 'Відновлюємо сеанс…',
      serverError: 'Сервер тимчасово недоступний. Спробуйте пізніше.',
      timeout: 'Час очікування запиту минув. Повторіть спробу.',
    },
  },
  common: {
    cancel: 'Скасувати',
    close: 'Закрити',
    continue: 'Продовжити',
    error: 'Помилка',
    info: 'Інформація',
    loading: 'Завантаження',
    no: 'Ні',
    retry: 'Повторити',
    save: 'Зберегти',
    somethingWentWrong: 'Щось пішло не так',
    success: 'Успішно',
    yes: 'Так',
  },
  home: {
    email: 'Електронна пошта',
    fullName: "Повне ім'я",
    language: 'Мова',
    logout: 'Вийти',
    logoutError:
      'Ви вийшли з облікового запису на цьому пристрої, але повідомити сервер не вдалося.',
    premium: 'Преміум',
    premiumActive: 'Активний',
    premiumInactive: 'Неактивний',
    title: 'Головна',
  },
  languages: {
    english: 'Англійська',
    french: 'Французька',
    german: 'Німецька',
    spanish: 'Іспанська',
    ukrainian: 'Українська',
  },
  showcase: {
    currentLanguage: 'Поточна мова',
    description: 'Демонстрація багаторазової основи застосунку',
    showError: 'Показати помилку',
    showSuccess: 'Показати успіх',
    title: 'Основа FastRep',
  },
};
